### ISSUE TITLE
SPSearchResultSource not Working without Global Search Center

### ISSUE THREAD

**Issue by NikCharlebois** [dsccommunity/SharePointDsc#870] opened 2018-09-12 15:16 UTC
#### Details of the scenario you tried and the problem that is occurring
If no global search center is defined, then the Get-TargetResource method from the SPSearchResultSource resource is not working.

#### Verbose logs showing the problem
N/A

#### Suggested solution to the issue
Drop the current way of retrieving the Search Owner (which uses the global search), in favor of:

```powershell
$fedman = New-Object Microsoft.Office.Server.Search.Administration.Query.FederationManager($ssa)
$searchOwner = Get-SPEnterpriseSearchOwner -Level SSA
$filter = New-Object Microsoft.Office.Server.Search.Administration.SearchObjectFilter($searchOwner)
$resultSources = $fedman.ListSources($filter,$true)
```

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
N/A

#### The operating system the target node is running
N/A

#### Version of SharePoint that is used (e.g. SharePoint 2016)
SP2013

#### Version and build of PowerShell the target node is running
PoSh 5.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
2.5.0.0

**Comment by ykuijs** [comment] 2018-11-02 14:01
@NikCharlebois Has this been implemented in your PR for SPSearchResultSource?

**Comment by NikCharlebois** [comment] 2018-11-02 17:49
@ykuijs , no it's still an ongoing issue.

**Comment by ykuijs** [comment] 2018-11-02 21:28
What is the difference between your suggested solution and the currently implemented code:
https://github.com/PowerShell/SharePointDsc/blob/dev/Modules/SharePointDsc/DSCResources/MSFT_SPSearchResultSource/MSFT_SPSearchResultSource.psm1#L80-L95

**Comment by ykuijs** [comment] 2019-09-19 12:30
@NikCharlebois Does this issue still exists? And what about the question I asked in the previous comment?

**Comment by ykuijs** [comment] 2020-10-28 10:23
The resource is already using the suggested code. Just tested the Get method on an environment where I deleted the global search center and it looks like the issue works as expected.

@NikCharlebois If you are able to reproduce the issue with v4.3, please let me know so we can troubleshoot the issue. Closing issue.

**Closed by ykuijs** 2020-10-28 10:23 UTC
Labels: bug, help wanted
