### ISSUE TITLE
SPInstallPrereqs: Get-SPDSCAssemblyVersion is not recognized

### ISSUE THREAD

**Issue by andikrueger** [dsccommunity/SharePointDsc#663] opened 2017-10-16 13:52 UTC
**Details of the scenario you try and problem that is occurring:**
Today, I saw this error several times:

```
[[SPInstallPrereqs]InstallPrereqs] Getting installation status of SharePoint prerequisites
The term 'Get-SPDSCAssemblyVersion' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path 
was included, verify that the path is correct and try again.
    + CategoryInfo          : ObjectNotFound: (Get-SPDSCAssemblyVersion:) [], CimException
    + FullyQualifiedErrorId : CommandNotFoundException
```
The error occurs on the first (and sometimes second) start of a DSC configuration. The issue is reproducible.

**The DSC configuration that is using the resource:**
Shortend configuration
```
Configuration SharePoint
{
    param( [string]$NodeName  )

    Import-DscResource -ModuleName SharePointDsc -ModuleVersion 1.8.0.0

    node $NodeName
    {
SPInstallPrereqs InstallPrereqs {
            Ensure        = "Present"
            OnlineMode    = $true
            InstallerPath = "$($binaryPath)\Sources\prerequisiteinstaller.exe"
            DependsOn     = @("[Script]DownloadSources", "[Group]LocalAdministrators") 
        }
}
}
```
**Version of the Operating System and PowerShell the DSC Target Node is running:**
WIN2012R2
PSVersion 5.1.14409.1005 

**Version of the DSC module you're using:**
1.8.0.0

**Comment by NikCharlebois** [comment] 2017-10-16 14:01
@andikrueger can you post the output of running the following PoSh commands on that box?
    Import-Module SharePointDSC -Force
    Get-Command | ?{$_.ModuleName -eq "SharePointDSC"}

Thanks

**Comment by andikrueger** [comment] 2017-10-16 14:04
```
PS C:\Users\admak.DEV> Import-Module SharePointDSC -Force

PS C:\Users\admak.DEV> Get-Command | ?{$_.ModuleName -eq "SharePointDSC"}

CommandType     Name                                               Version    Source                                                                                                          
-----------     ----                                               -------    ------                                                                                                          
Function        Add-SPDSCUserToLocalAdmin                          1.8.0.0    SharePointDSC                                                                                                   
Function        Get-SPDSCAssemblyVersion                           1.8.0.0    SharePointDSC                                                                                                   
Function        Get-SPDSCContentService                            1.8.0.0    SharePointDSC                                                                                                   
Function        Get-SPDscFarmProductsInfo                          1.8.0.0    SharePointDSC                                                                                                   
Function        Get-SPDscFarmVersionInfo                           1.8.0.0    SharePointDSC                                                                                                   
Function        Get-SPDSCInstalledProductVersion                   1.8.0.0    SharePointDSC                                                                                                   
Function        Get-SPDscOSVersion                                 1.8.0.0    SharePointDSC                                                                                                   
Function        Get-SPDSCRegistryKey                               1.8.0.0    SharePointDSC                                                                                                   
Function        Get-SPDscRegProductsInfo                           1.8.0.0    SharePointDSC                                                                                                   
Function        Get-SPDSCServiceContext                            1.8.0.0    SharePointDSC                                                                                                   
Function        Get-SPDSCUserProfileSubTypeManager                 1.8.0.0    SharePointDSC                                                                                                   
Function        Invoke-SPDSCCommand                                1.8.0.0    SharePointDSC                                                                                                   
Function        Remove-SPDSCGenericObject                          1.8.0.0    SharePointDSC                                                                                                   
Function        Remove-SPDSCUserToLocalAdmin                       1.8.0.0    SharePointDSC                                                                                                   
Function        Rename-SPDSCParamValue                             1.8.0.0    SharePointDSC                                                                                                   
Function        Resolve-SPDscSecurityIdentifier                    1.8.0.0    SharePointDSC                                                                                                   
Function        Set-SPDscObjectPropertyIfValuePresent              1.8.0.0    SharePointDSC                                                                                                   
Function        Test-SPDSCIsADUser                                 1.8.0.0    SharePointDSC                                                                                                   
Function        Test-SPDSCObjectHasProperty                        1.8.0.0    SharePointDSC                                                                                                   
Function        Test-SPDscParameterState                           1.8.0.0    SharePointDSC                                                                                                   
Function        Test-SPDSCRunAsCredential                          1.8.0.0    SharePointDSC                                                                                                   
Function        Test-SPDSCRunningAsFarmAccount                     1.8.0.0    SharePointDSC                                                                                                   
Function        Test-SPDSCUserIsLocalAdmin                         1.8.0.0    SharePointDSC                                                                                                   

```

**Comment by NikCharlebois** [comment] 2017-10-16 14:05
@andikrueger Thanks, would you mind posting your entire Configuration?

**Comment by andikrueger** [comment] 2017-10-16 14:25
Please find attached the configuration. I skipped the parts after SPCreateFarm.

The configuration should target future dev environments. The systems are based on azure WIN2012R2 boxes with SQL2014 preinstalled. 

[SharePointPreperation.txt](https://github.com/PowerShell/SharePointDsc/files/1387771/SharePointPreperation.txt)

Let me know if you want to have a look at the server. I'm glad to help.

**Comment by andikrueger** [comment] 2017-10-16 20:44
Further investigation showed an error with the script resource block:
1. The script resource block did not show any error on my first VM. On another VM the script resource did throw an error: "The term 'Install-Module' is not recognized as the name of a cmdlet..."
a) Adding the PsDscRunAsCredential did resolve the error.
b) I do not understand why this error did not occur on the first VM
2. The configuration did use the variable $domainAdminCred that was never initiated or set.

Changing 1. and 2. did solve the initial issue.

**Comment by SvenLauterbach** [comment] 2018-10-15 08:56
Hi,

I'm having the same issue, but can't find the cause of this error in my config. 

```VERBOSE: [EURMDIMDEVDK4W]: LCM:  [ Start  Resource ]  [[SPInstallPrereqs]PrerequisitesInstallation]
VERBOSE: [EURMDIMDEVDK4W]: LCM:  [ Start  Test     ]  [[SPInstallPrereqs]PrerequisitesInstallation]
VERBOSE: [EURMDIMDEVDK4W]:                            [[SPInstallPrereqs]PrerequisitesInstallation] Importing the module MSFT_SPInstallPrereqs in force mode.
VERBOSE: [EURMDIMDEVDK4W]:                            [[SPInstallPrereqs]PrerequisitesInstallation] Importing the module MSFT_SPInstallPrereqs in force mode.
VERBOSE: [EURMDIMDEVDK4W]:                            [[SPInstallPrereqs]PrerequisitesInstallation] Testing installation status of SharePoint prerequisites
VERBOSE: [EURMDIMDEVDK4W]:                            [[SPInstallPrereqs]PrerequisitesInstallation] Getting installation status of SharePoint prerequisites
The term 'Get-SPDSCAssemblyVersion' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
    + CategoryInfo          : ObjectNotFound: (Get-SPDSCAssemblyVersion:) [], CimException
    + FullyQualifiedErrorId : CommandNotFoundException
    + PSComputerName        : eurmdimdevdk4w
 
VERBOSE: [EURMDIMDEVDK4W]:                            [[SPInstallPrereqs]PrerequisitesInstallation] Getting installed windows features
The term 'Get-SPDscOSVersion' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
    + CategoryInfo          : ObjectNotFound: (Get-SPDscOSVersion:) [], CimException
    + FullyQualifiedErrorId : CommandNotFoundException
    + PSComputerName        : eurmdimdevdk4w
 
VERBOSE: [EURMDIMDEVDK4W]:                            [[SPInstallPrereqs]PrerequisitesInstallation] Checking windows packages from the registry
VERBOSE: [EURMDIMDEVDK4W]:                            [[SPInstallPrereqs]PrerequisitesInstallation] Prerequisite AppFabric 1.1 for Windows Server was not found on this system
VERBOSE: [EURMDIMDEVDK4W]:                            [[SPInstallPrereqs]PrerequisitesInstallation] Prerequisite Microsoft CCR and DSS Runtime 2008 R3 was not found on this system
VERBOSE: [EURMDIMDEVDK4W]:                            [[SPInstallPrereqs]PrerequisitesInstallation] Prerequisite Microsoft Identity Extensions was not found on this system
VERBOSE: [EURMDIMDEVDK4W]:                            [[SPInstallPrereqs]PrerequisitesInstallation] Prerequisite Microsoft Sync Framework Runtime v1.0 SP1 (x64) was not found on this system
VERBOSE: [EURMDIMDEVDK4W]:                            [[SPInstallPrereqs]PrerequisitesInstallation] Prerequisite WCF Data Services 5.6.0 Runtime was not found on this system
The term 'Test-SPDscParameterState' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
    + CategoryInfo          : ObjectNotFound: (Test-SPDscParameterState:) [], CimException
    + FullyQualifiedErrorId : CommandNotFoundException
    + PSComputerName        : eurmdimdevdk4w
 
VERBOSE: [EURMDIMDEVDK4W]: LCM:  [ End    Test     ]  [[SPInstallPrereqs]PrerequisitesInstallation]  in 0.6720 seconds.
The PowerShell DSC resource '[SPInstallPrereqs]PrerequisitesInstallation' with SourceInfo 'D:\DSC\IMDevEnv.ps1::170::9::SPInstallPrereqs' threw one or more non-terminating errors while running the Test-TargetResource functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : eurmdimdevdk4w
```

**The DSC configuration that is using the resource:**
https://gist.github.com/SvenLauterbach/34d9bd86cd58d134d975574f273ff4e3

The output of the requested command:

```
PS C:\Users\Lauterbach Sven> Import-Module SharePointDSC -Force
PS C:\Users\Lauterbach Sven> Get-Command | ?{$_.ModuleName -eq "SharePointDSC"}

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Add-SPDSCUserToLocalAdmin                          2.5.0.0    SharePointDSC
Function        Clear-SPDscKerberosToken                           2.5.0.0    SharePointDSC
Function        Convert-SPDscADGroupIDToName                       2.5.0.0    SharePointDSC
Function        Convert-SPDscADGroupNameToID                       2.5.0.0    SharePointDSC
Function        ConvertTo-ReverseString                            2.5.0.0    SharePointDSC
Function        ConvertTo-TwoDigitFlipString                       2.5.0.0    SharePointDSC
Function        Format-OfficePatchGUID                             2.5.0.0    SharePointDSC
Function        Get-SPDSCAssemblyVersion                           2.5.0.0    SharePointDSC
Function        Get-SPDSCContentService                            2.5.0.0    SharePointDSC
Function        Get-SPDscFarmAccount                               2.5.0.0    SharePointDSC
Function        Get-SPDscFarmAccountName                           2.5.0.0    SharePointDSC
Function        Get-SPDscFarmProductsInfo                          2.5.0.0    SharePointDSC
Function        Get-SPDscFarmVersionInfo                           2.5.0.0    SharePointDSC
Function        Get-SPDSCInstalledProductVersion                   2.5.0.0    SharePointDSC
Function        Get-SPDscOSVersion                                 2.5.0.0    SharePointDSC
Function        Get-SPDSCRegistryKey                               2.5.0.0    SharePointDSC
Function        Get-SPDscRegProductsInfo                           2.5.0.0    SharePointDSC
Function        Get-SPDSCServiceContext                            2.5.0.0    SharePointDSC
Function        Get-SPDSCUserProfileSubTypeManager                 2.5.0.0    SharePointDSC
Function        Invoke-SPDSCCommand                                2.5.0.0    SharePointDSC
Function        Remove-SPDSCGenericObject                          2.5.0.0    SharePointDSC
Function        Remove-SPDSCUserToLocalAdmin                       2.5.0.0    SharePointDSC
Function        Rename-SPDSCParamValue                             2.5.0.0    SharePointDSC
Function        Resolve-SPDscSecurityIdentifier                    2.5.0.0    SharePointDSC
Function        Set-SPDscObjectPropertyIfValuePresent              2.5.0.0    SharePointDSC
Function        Test-SPDSCIsADUser                                 2.5.0.0    SharePointDSC
Function        Test-SPDSCObjectHasProperty                        2.5.0.0    SharePointDSC
Function        Test-SPDscParameterState                           2.5.0.0    SharePointDSC
Function        Test-SPDSCRunAsCredential                          2.5.0.0    SharePointDSC
Function        Test-SPDSCRunningAsFarmAccount                     2.5.0.0    SharePointDSC
Function        Test-SPDSCUserIsLocalAdmin                         2.5.0.0    SharePointDSC
```

**Version of the Operating System and PowerShell the DSC Target Node is running:**
WIN2012R2
5.1.14409.1012

**Version of the DSC module you're using:**
2.5.0.0

Please let me know if you need more informations.

**Comment by SvenLauterbach** [comment] 2018-10-15 10:55
@NikCharlebois should I open a new Issue?

**Comment by ykuijs** [comment] 2018-10-17 20:47
Hi @SvenLauterbach I will reopen this issue, so we can start investigating the issue.

**Comment by ykuijs** [comment] 2018-10-17 20:56
This looks like a timing or scope issue: Either the nested modules are not yet loaded when the resource code is executing or the nested module is loaded in a different scope. Will have to think about a method to tackle this issue. Maybe you can use test with a config that just contains the SPInstallPrereqs resource and see if the issue occurs then. If so, start debugging the resource using this method https://docs.microsoft.com/en-us/powershell/dsc/debugresource

**Comment by SvenLauterbach** [comment] 2018-10-23 19:56
Removing everything from the config except the SPInstallPrereqs works, is there some kind of workaround for timing/scope issues?

**Comment by ykuijs** [comment] 2018-10-29 19:38
@SvenLauterbach Are you using the DependsOn parameters? Can you share your config? Can you try to add the resources one by one back into your config and try again? I am wondering if there is a specific resource that triggers this issue or maybe a certain number of resources?

Haven't seen this type of issue before, so not sure what we can do to troubleshoot the issue.

**Comment by SvenLauterbach** [comment] 2018-11-09 16:20
Ok, I tried adding back the resources and it only required one resource to trigger the error:

```
SQLSetup SQLSetup
{
	InstanceName = "MSSQLServer"
	SourcePath = 'D:\DSC\SQL Server Setup'
	UpdateEnabled = $true
	UpdateSource = 'D:\DSC\SQL Server Setup\Updates'
	Features = "SQLENGINE"
	SQLCollation = "Latin1_General_CI_AS"
	InstallSharedDir = "D:\Program Files\Microsoft SQL Server"
	InstallSharedWOWDir  = 'D:\Program Files (x86)\Microsoft SQL Server'
	InstanceDir          = 'D:\Program Files\Microsoft SQL Server'
	SQLSysAdminAccounts = @($Node.Owner, $setup_account.UserName)
	PsDscRunAsCredential = $setup_account
   # DependsOn = @("[FireWall]SQLFirewallRule", "[cNtfsPermissionEntry]DDrivePermissionSet", "[cNtfsPermissionEntry]DefaultUserFolderPermissionSet");           
}

SPInstallPrereqs PrerequisitesInstallation
{
	InstallerPath = "D:\DSC\SharePoint 2013 setup\prerequisiteinstaller.exe"
	OnlineMode = $True
	Ensure = "Present"
	PsDscRunAsCredential = $setup_account 
	DependsOn = @("[SQLSetup]SQLSetup")
}
```

Right after adding the SQLSetup resource the error occured. Hope this helps.

**Comment by ykuijs** [comment] 2019-01-09 20:03
Hi @SvenLauterbach Sorry for not replying earlier.....hectic end of the year and then the holiday season ;-)

Does the issue still exist? Did you try to add another resource than SQLSetup resource (so we can eliminate if this is related to SQLSetup or not)?

**Comment by SvenLauterbach** [comment] 2019-01-22 08:56
Hi @ykuijs , I was on vacation, i will investigate the issue later today and provide some feedback.

**Comment by ykuijs** [comment] 2019-07-08 12:32
In issue https://github.com/PowerShell/SharePointDsc/issues/912#issuecomment-509200770  @goorallab reported that this was caused by using the same PSRunAsCredential for both the SQLServerDsc and SharePointDsc resources.

@SvenLauterbach I see in your config that you were using the same account as well. Can you please test with different accounts and validate that this solves the issue?

**Comment by SvenLauterbach** [comment] 2019-07-18 18:56
I will try it

**Comment by SvenLauterbach** [comment] 2019-08-08 13:36
My configuration has also the same account in both resources in PSRunAsCredential. It takes some time to get a second account setup

**Comment by SvenLauterbach** [comment] 2019-09-16 11:25
Small Update. I removed the `PSRunAsCredential` from the SQLServerDSC commands (so that they should run under the SYSTEM account?) and used the `PSRunAsCredential` only on the SharePoint DSC resources. 

However, still the same issue. I will try to create a minimal example and post the Verbose output later.

**Comment by ykuijs** [comment] 2019-09-19 10:28
Can you use a different service account for SQLServerDsc, not the System account?

**Comment by SvenLauterbach** [comment] 2019-12-11 10:14
I ran the SQLServerDSC under a different account than the SharePointDSC resource, still getting the same error.

**Comment by ykuijs** [comment] 2020-07-31 15:15
Have been able to create a reproduction!

Environment: Single server with SQL 2012 SP4 and SharePoint 2013 SP1, SQLServerDsc v14.2.0, SharePointDsc (Dev version), SQLPS installed via https://sqlpadawan.com/2018/08/01/how-to-install-sql-server-sqlps-powershell-module/

- Scenario 1: Using SQLPS, one SQL and one SP resource, using same PSDscCredential account: Error is thrown.
- Scenario 2: Using SQLPS, one SQL and one SP resource, using different PSDscCredential account: All works well.
- Scenario 3: Installed SQLServer module, one SQL and one SP resource, using same PSDscCredential account: All works well.

So workarounds for now: Use different PsDscRunAsCredential or install SQLServer module

Now trying to find the root cause.

**Comment by ykuijs** [comment] 2020-08-10 15:05
Did some more troubleshooting:
When loading the SQLPS module, the PSModulePath variable is changed to this value:
```
C:\windows\system32\WindowsPowerShell\v1.0\Modules\;C:\Program Files (x86)\Microsoft SQL Server\110\T
ools\PowerShell\Modules\;C:\Program Files\AppFabric 1.1 for Windows Server\PowershellModules;C:\Program Files\Microsoft SQL Server\110\Tools\PowerShell\Modules\
```

It looks however that this is placed back to the original value with time. When I debug the resource and step through the code, after a couple of seconds, the PSModulePath value is correct again. Since the SQLPS module is a binary module, I have to use reflector to look into the code behind.

@johlju Do you have any clue why this is happening or can explain what is going on?

**Comment by ykuijs** [comment] 2020-08-10 15:34
Just to make sure:
Because the PSModulePath is updated, the SharePointDsc module cannot be found and therefore all the functions inside the Utils module are also not found.

For now the best solution is to update to the SQLServer module, since the SQLPS is [no longer updated](https://docs.microsoft.com/en-us/sql/powershell/sql-server-powershell?view=sql-server-ver15):

> There are two SQL Server PowerShell modules; SqlServer and SQLPS. The SQLPS module is included with the SQL Server installation (for backwards compatibility), but is no longer being updated. The most up-to-date PowerShell module is the SqlServer module. The SqlServer module contains updated versions of the cmdlets in SQLPS, and also includes new cmdlets to support the latest SQL features.

Can anyone that encountered this issue test if it also occurs when using SQLServer instead of SQLPS??

**Comment by johlju** [comment] 2020-08-10 18:54
> It looks however that this is placed back to the original value with time. When I debug the resource and step through the code, after a couple of seconds, the PSModulePath value is correct again.

I have never encountered that the path is changed when importing SQLPS module. `$PSModulePath` should always contain the path to the SQLPS module (as far as I know it is set during install of SQL Server). I have never seen it changing `$PSModulePath` during import.

**Comment by ykuijs** [comment] 2020-10-27 15:48
This issue is most probably caused by the fact that SQLPS is used and both the SQL and SP resources are using the same PsDscRunAsCredential. More details are described [here](https://github.com/dsccommunity/SharePointDsc/issues/663#issuecomment-667173870).

Closing the issue since the solution is to use the SQLServer module instead and SQLPS is no longer updated.

Please add comments if these solutions don't work, so we can investigate further.

**Closed by ykuijs** 2020-10-27 15:48 UTC
Labels: bug, needs investigation, needs more information
