### ISSUE TITLE
SharePoint marketing site collection not able to set as home site

### ISSUE THREAD

**Issue by soundd2** [dsccommunity/SharePointDsc#1386] opened 2022-02-21 05:50 UTC
I believe below script is intended to set site collection as home site in the SharePoint online. If I am wrong please correct.
I am trying to do using SharePoint DSC PowerShell , however it is failing due to credentials issue although provided correctly. please help.
Account I am giving is part of global admin

I can do it by trinational method, but at this point I am trying to test with `DSC.```

Below is the code:

# using DSC setting SharePoint site collection home site as home site
```PowerShell
Configuration Example
{
    param(
        [Parameter(Mandatory = $true)]
        [PSCredential]
        $credsGlobalAdmin
    )
    Import-DscResource -ModuleName Microsoft365DSC

    node localhost
    {
        SPOHomeSite "SetMarketingSiteCollectionAsHomeSite"
        {
            IsSingleInstance     = "Yes"
            Url                  = "https://domain.sharepoint.com/sites/Marketing"
            Ensure               = "Present"
            Credential           = $credsGlobalAdmin
        }
    }
}
```

# Compiling 
Example

**Comment by ykuijs** [comment] 2022-02-21 12:00
Hi @soundd2,

You are using Microsoft365DSC, this repository is for SharePointDsc which is a different module.

Please create issues for Microsoft365DSC at: https://github.com/microsoft/Microsoft365DSC and provide any error messages you are getting.

You can find the documentation for this SPOHomeSite resource here: https://microsoft365dsc.com/resources/sharepoint/SPOHomeSite/

**Comment by soundd2** [comment] 2022-02-21 13:21
HI Yorick Kuijs,

I believe below script is intended to set site collection as home site in
the SharePoint online. If I am wrong please correct.
I am trying to do using SharePoint DSC PowerShell , however it is failing
due to credentials issue although provided correctly. please help.
Account I am giving is part of global admin

I can do it by trinational method, but at this point I am trying to test
with DSC.
[image: image.png]



Regards

Shyam.CH

**Comment by ykuijs** [comment] 2022-02-21 20:48
SharePointDsc (this repository) is targeting on-premise SharePoint: 2013, 2016, 2019 or Subscription Edition.

However you are trying to configure SharePoint Online, which is part of Microsoft 365 and which can be configured using Microsoft365DSC. This is also mentioned in your configuration:
> Import-DscResource -ModuleName _**Microsoft365DSC**_

**Comment by ykuijs** [comment] 2022-02-22 09:20
Closing this here since the issue is being handled in Microsoft365DSC

**Closed by ykuijs** 2022-02-22 09:20 UTC
