### ISSUE TITLE
SPFarm: The term 'Get-SPDSCInstalledProductVersion' is not recognized as the name of a cmdlet, function, script file

### ISSUE THREAD

**Issue by bminisi** [dsccommunity/SharePointDsc#912] opened 2018-10-15 02:28 UTC
this is the same issue as #678.  I ran this same configuration script on an Azure VM on Win 2012 R2 and it works with SharePoint 2013.  I am now trying to run in on the same OS version for an on-premise VM.  This configuration starts with a Sql Server install/configuration and that works without a problem.

Issue #678 details exactly what I am experiencing.  I can run the product version cmdlet with both my account, the system account and Ps credential account and it returns the correct version.

Another unique detail I am experiencing is it fails even before SPFarm with the pre-req installation.  It exits with an error code of -1.  However, I can install it manually.  At a loss.  I believe there are two issues focused on this, but they are both closed without a resolution.

SharepointDsc version 2.4.  The only resource that seems to work is install binaries.

This is a pull client machine pulling from an on-premise pull server.  In the Azure VM, where it works, that is using Azure Automation DSC as the pull server.

SharepointDsc is coming from the PowerShell gallery version 2.4.

The VMs are located in Germany, but they are set to English.

**Comment by ykuijs** [comment] 2018-10-17 20:29
Hi @bminisi Can you share you config and verbose logging?

**Comment by bminisi** [comment] 2018-10-18 20:43
Here is the configuration file.  This is only showing up to the area where it fails.

[DevMachineSetup.ps1.txt](https://github.com/PowerShell/SharePointDsc/files/2493490/DevMachineSetup.ps1.txt)

I also attached the Configuration Status file.

[{38BA9962-D313-11E8-810F-0050569928CE}-0.details.json.txt](https://github.com/PowerShell/SharePointDsc/files/2493546/38BA9962-D313-11E8-810F-0050569928CE.-0.details.json.txt)

**Comment by bminisi** [comment] 2018-12-21 21:13
I just experience the same problem on another machine.  Most do not have this problem, but all of these machines are built off of the same template.

**Comment by ykuijs** [comment] 2019-01-12 12:08
This issue looks similar to #663 

@bminisi Can you please check:
- What happens if you just use the SPFarm resource in a config?
- What happens if you then add the SQLSetup resource to the config with just the SPFarm resource?
- What happens if you add the SPInstall resource to the config with just the SPFarm resource?

**Comment by goorallab** [comment] 2019-07-08 12:14
Hello,

Similar issue blocked me for couple of days, but on the upside, I did managed troubleshoot it.
In my DSC config I was trying installing SQL (using SQLServerDSC) and then SharePoint.
**Turns out that if you try to use same account for configuring SQL using SQLPS PowerShell Module and Installing SharePoint this issue occurs.**

In SQLServerDSC if you do an **SqlServerMaxDop** without **SqlServer** PowerShell module it will fall back to old **SQLPS** Module which apparently does some wierd thing to scoping in PowerShell.

Using different account than SharePoint Setup/Install Account in **PsDscRunAsCredential** in **SqlServerMaxDop** fixed issue for me.
Not using **PsDscRunAsCredential** in **SqlServerMaxDop** also did the trick.
And of course having **SqlServer** PowerShell module installed on server resolves issue as well.

I can see that @bminisi did similar thing by using SharePoint Setup/Install Account in **SqlSetup**, **SqlServerNetwork** and **SqlWindowsFirewall**, so It just might be the same issue.

Hope this helps,
Happy automating!

**Comment by ykuijs** [comment] 2019-07-08 12:24
@goorallab This is great work, thanks a lot for investigating and sharing your results!!

We will see if we need to update documentation or if we can implement a code fix.

Again, thanks a million!!

**Comment by ykuijs** [comment] 2019-07-25 13:06
I tried to reproduce this issue, so I could troubleshoot it. Unfortunately I was unable to. Could you please check my reproduction steps to see if anything is different on your end:

- OS: Windows Server 2012 R2, which is also a DC for a custom domain
- SQL: SQL Server 2012 with SP4
- SharePoint: SP2013 Enterprise with SP1

$cred is my admin account, which has local admin permissions

```PowerShell
configuration DevMachineSetup
{

    param
    (
        [Parameter(Mandatory = $true)]
        [PSCredential]
        $SetupAccount
    )
   
    Import-DscResource -ModuleName SqlServerDsc
    Import-DscResource -ModuleName SharePointDsc
    Import-DscResource -ModuleName PsDesiredStateConfiguration

    Node localhost
    {
        SqlSetup 'InstallDefaultInstance'
        {
            InstanceName          = 'MSSQLSERVER'
            Features              = 'SQLENGINE,SSMS'
            SecurityMode          = 'SQL'
            SAPwd                 = $SetupAccount
            SQLCollation          = 'Latin1_General_CI_AS_WS'
            SQLSvcAccount         = $SetupAccount
            AgtSvcAccount         = $SetupAccount
            SQLSysAdminAccounts   = 'Administrators'
            InstallSharedDir      = 'C:\Program Files\Microsoft SQL Server'
            InstallSharedWOWDir   = 'C:\Program Files (x86)\Microsoft SQL Server'
            InstanceDir           = 'C:\Program Files\Microsoft SQL Server'
            InstallSQLDataDir     = 'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Data'
            SQLUserDBDir          = 'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Data'
            SQLUserDBLogDir       = 'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Data'
            SQLTempDBDir          = 'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Temp'
            SQLTempDBLogDir       = 'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Log'
            SQLBackupDir          = 'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Backup'
            SourcePath            = 'C:\Install\SQL2012SP4'
            UpdateEnabled         = 'False'
            ForceReboot           = $true
            SQMReporting          = $false
            ErrorReporting        = $false
            BrowserSvcStartupType = 'Disabled'
            PsDscRunAsCredential  = $SetupAccount
        }

        SqlServerMaxDop MaxDOP
        {
            Ensure               = 'Present'
            MaxDop               = 1
            ServerName           = 'localhost'
            InstanceName         = 'MSSQLSERVER'
            PsDscRunAsCredential = $SetupAccount
            DependsOn            = '[SqlSetup]InstallDefaultInstance'
        }

        SPInstallPrereqs InstallPrerequisites
        {
            IsSingleInstance     = "Yes"
            InstallerPath        = 'C:\Install\SP2013SP1\prerequisiteinstaller.exe'
            OnlineMode           = $true
            Ensure               = 'Present'
            PsDscRunAsCredential = $SetupAccount
            DependsOn            = '[SqlServerMaxDop]MaxDOP'
        }

        Registry DisableLoopback
        {
            Ensure               = 'Present'
            Key                  = 'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa'
            ValueName            = 'DisableLoopbackCheck'
            ValueData            = 1
            ValueType            = 'DWord'
        }

        SPInstall InstallBinaries
        {
            IsSingleInstance     = "Yes"
            BinaryDir            = "C:\Install\SP2013SP1"
            ProductKey           = 'XXXXX-XXXXX-XXXXX-XXXXX-XXXXX'
            PsDscRunAsCredential = $SetupAccount
            DependsOn            = '[SPInstallPrereqs]InstallPrerequisites'      
        }
        
        SPFarm SharePointFarm
        {
            IsSingleInstance          = "Yes"
            Ensure                    = "Present"
            DatabaseServer            = 'DSCTest'
            FarmConfigDatabaseName    = "SP_Config"
            AdminContentDatabaseName  = "SP_AdminContent"
            Passphrase                = $SetupAccount
            FarmAccount               = $SetupAccount
            RunCentralAdmin           = $true
            CentralAdministrationPort = 8000
            CentralAdministrationAuth = 'NTLM'
            PsDscRunAsCredential      = $SetupAccount
            DependsOn                 = '[SPInstall]InstallBinaries'
        }
    }
}

$ConfigurationData = @{
        AllNodes = @(
            @{
                # The "*" means "all nodes named in ConfigData" so we don't have to repeat ourselves
                NodeName="localhost"
                PSDscAllowPlainTextPassword = $true
                PsDscAllowDomainUser = $true
            }
            )
        }

DevMachineSetup -ConfigurationData $ConfigurationData -OutputPath c:\Temp\Dsc -SetupAccount $cred
```

**Comment by goorallab** [comment] 2019-07-26 09:47
@ykuijs 
Can you make sure that you don't have module **SqlServer** installed on server nor install account scope? 
Can you share Verbose output form DSC run?

I will check my dev server specs and paste dsc config later.

**Comment by ykuijs** [comment] 2020-07-31 15:16
Managed to reproduce the issue. More info [here](https://github.com/dsccommunity/SharePointDsc/issues/663#issuecomment-667173870).

**Comment by ykuijs** [comment] 2020-08-10 15:38
@bminisi I need some confirmation for a possible solution/root cause.

Were you using SQLPS to manage the SQL installation? It looks like that is the cause. For now the best solution is to update to the SQLServer module, since the SQLPS is no longer updated:

> There are two SQL Server PowerShell modules; SqlServer and SQLPS. The SQLPS module is included with the SQL Server installation (for backwards compatibility), but is no longer being updated. The most up-to-date PowerShell module is the SqlServer module. The SqlServer module contains updated versions of the cmdlets in SQLPS, and also includes new cmdlets to support the latest SQL features.

Can you this issue test if it also occurs when using SQLServer instead of SQLPS??

**Comment by ykuijs** [comment] 2020-10-27 15:47
This issue is most probably caused by the fact that SQLPS is used and both the SQL and SP resources are using the same PsDscRunAsCredential. More details are described [here](https://github.com/dsccommunity/SharePointDsc/issues/663#issuecomment-667173870).

Closing the issue since the solution is to use the SQLServer module instead and SQLPS is no longer updated.

**Closed by ykuijs** 2020-10-27 15:47 UTC
Labels: bug, needs investigation
