### ISSUE TITLE
New MinRole farm is created but not in compliance

### ISSUE THREAD

**Issue by regularroutine** [dsccommunity/SharePointDsc#1002] opened 2019-01-07 15:17 UTC
Hello,
I have been playing around with Lability and SharePointDsc. Everything is working great except that my servers are deployed with MinRoles showing as not in compliance. If I compare the service applications and services before and after clicking "Fix" I see no differences. 
Does anyone know how I can find the root cause for these compliance issues?

Also, a separate question is there currently a EnableDeveloperDashboard option?

Thanks,
David

**Comment by andikrueger** [comment] 2019-01-08 13:01
I did see this behaviour before. I was able to fix this issue by running the config wizard after the installation.

**Comment by ykuijs** [comment] 2019-01-08 20:15
I haven't seen this behavior before.

Currently we do not have a possibility to configure the developer dashboard. This would be a good addition for the SPFarm resource, since this is a farm wide setting. Will create a new issue, so we can track implementation.

**Comment by ykuijs** [comment] 2019-01-08 20:22
Just created #1006 for tracking the ability to configure the dev dashboard

**Comment by ykuijs** [comment] 2019-01-08 20:23
For troubleshooting the issue: Do you see any information in the ULS log?

**Comment by andikrueger** [comment] 2019-01-09 08:36
I've already spent quite a bit of time on the problem. As far as I know there is no information in the ULS or in eventviewer that points to a problem. 

As far as I know, the problem occurs when SharePoint (SPInstall) is installed, followed by a Language Pack (SPInstallLanguagePack) and then the creation of the farm (SPFarm). Checking the compliance status of the min role at this particular time will result in a not compliant state.

**Comment by ykuijs** [comment] 2019-01-09 16:14
Which will be resolved by running the Config Wizard?

Did you try to use the SPConfigWizard resource, in other words: Are the registry keys which specify the requirement for running the Config Wizard set?

**Comment by ykuijs** [comment] 2019-01-18 13:19
Have you tried to manually reproduce these steps, so installing SP, LP and then creating the farm?

And is this SP2016 or SP2019 or both?

**Comment by andikrueger** [comment] 2019-01-18 13:38
I first saw this issue with SP 2016 and very recently with SP 2019 - I will try to recreate these steps manually to be sure it is not something related to DSC.

**Comment by ykuijs** [comment] 2019-04-09 21:30
@andikrueger Have you been able to test this issue yet?

**Comment by andikrueger** [comment] 2019-04-09 22:21
Have not been able to test it yet. Recently I stumbled on this issue with slipstreamed installations: https://support.microsoft.com/en-us/help/4019532/sharepoint-foundation-administration-tool-has-stopped-working-error

My environments are mostly installed by using slipstreaming. During my latest test I could resolve the error by running psconfig wizard several times.

**Comment by mariusv-msft** [comment] 2019-04-09 22:34
@ykuijs I've managed to reproduce this issue with each of my farm builds for SP 2019 on Win 2016 and Win 2019 and not slipstreaming. 
I had the issue with and without language packs installed, whether I use sp dsc or manual install and config. I don't think its a sp dsc resource issue. 

I've also tried to use the SPConfigWizard resource, but because there is no updates outstanding the Set-TargetResource wasn't executed. Also tried the SPMinRoleCompliance resource, but that also skipped the Set-TargetResource.

**Comment by andikrueger** [comment] 2019-04-09 22:57
At what point of your configuration did you check the farm compliance status and did the farm ever get compliant?

**Comment by mariusv-msft** [comment] 2019-04-10 15:35
I checked after farm creation, checked when other servers joined and then after the whole config completed with errors, Search Provisioning failed and Site Collections creation failed, similar to #990. 
The ApplicationWithSearch server, also hosting Central Admin, indicates not compliant with every check.

I restarted all the servers, no luck. 
Ran Config wizard once and that resolved the server compliant state.
Reran config and then Search and Site collection provisioned correctly.

I tried this on a 2 server farm, 4 server farm and 8 server farm. Every time, at least one server is out of compliance. Running Config Wizard usually solves it immediately.

**Comment by ykuijs** [comment] 2019-04-10 18:32
Earlier this week I deployed a new four server farm (FE, BE, Search FE and Search BE) using SPDsc: SharePoint 2019 on Windows Server 2016.

I used SPInstall, SPInstallLanguagePack and the updated SPProductUpdate to deploy the March CU before creating the farm. And indeed I experienced the same issue. Several service instances could not be started. During checking what was going on, I noticed that many service instance were available on those servers (both in Central Admin and via PowerShell) and therefore SPDsc couldn't start them. After running the Config Wizard, the service instances existed and could be started without any issues.

@mariusv-msft Are you also using a non-RTM deployment? And did you already report this issue somewhere?

**Comment by ykuijs** [comment] 2019-04-10 19:17
More info: Before last weeks deployment I did two more deployments, but using the old version of SPProductUpdate. So first installing SP, SP Language Pack, Create Farm, install CU. Using that config, I did not encounter this issue during both deployments

**Comment by mariusv-msft** [comment] 2019-04-10 20:55
Was using the latest image from MSDN and then applying KB 4462199 - SharePoint Server 2019 and KB 4462170 - SharePoint Server 2019 MUI/language patch.

Haven't reported it anywhere else.

I gather by doing the product updates after the farm creation you in effect running config wizard?

**Comment by ykuijs** [comment] 2020-10-27 15:39
Closing this issue since it is caused by SharePoint itself. If there is a way to resolve this issue using PowerShell, please add as a comment so we can implement it.

**Closed by ykuijs** 2020-10-27 15:39 UTC
Labels: bug, external, needs investigation
