### ISSUE TITLE
Getting error Invoke-CimMethod : Value cannot be null. Parameter name: service for SPFarm resource

### ISSUE THREAD

**Issue by Harish9211** [dsccommunity/SharePointDsc#1075] opened 2019-06-11 06:37 UTC
ISSUE TITLE:
   SPFARM - Getting error Invoke-CimMethod : Value cannot be null. Parameter name: service for SPFarm resource

    ISSUE DESCRIPTION (this template):
  Getting error Invoke-CimMethod : Value cannot be null. Parameter name: service for SPFarm resource

#### Verbose logs showing the problem

VERBOSE: [ComputerName]:                            [[SPFarm]SharePointFarm] Detected Version: SharePoint 2016 - c
onfiguring server as Application
VERBOSE: [ComputerName]:                            [[SPFarm]SharePointFarm] The SharePoint config database 'Share
Point_Config' already exists, so this server will join the farm.
VERBOSE: [ComputerName]:                            [[SPFarm]SharePointFarm] The database exists, so attempt to jo
in the server to the farm
VERBOSE: [ComputerName]:                            [[SPFarm]SharePointFarm] The server will attempt to join the f
arm now once every 60 seconds for the next 15 minutes.
VERBOSE: [ComputerName]:                            [[SPFarm]SharePointFarm] Leaving BeginProcessing Method of Con
nect-SPConfigurationDatabase.
VERBOSE: [ComputerName]:                            [[SPFarm]SharePointFarm] Entering function SPMountSPConfigurat
ionDatabase.InternalProcessRecord
VERBOSE: [ComputerName]:                            [[SPFarm]SharePointFarm] Creating connection string for config
 db SharePoint_Config server SQLServer
VERBOSE: [ComputerName]:                            [[SPFarm]SharePointFarm] Creating connection string for admin 
content db admincontentdatabase server SQLServer
VERBOSE: [ComputerName]:                            [[SPFarm]SharePointFarm] Using NTLM for sql connection string
VERBOSE: [ComputerName]:                            [[SPFarm]SharePointFarm] Openning configdb so that I can join 
it at server SQLServer database SharePoint_Config in farm mode
VERBOSE: [ComputerName]:                            [[SPFarm]SharePointFarm] Now joining to farm at server SQLServer database SharePoint_Config
Invoke-CimMethod : Value cannot be null.
Parameter name: service
At char:9
+         Invoke-CimMethod @parameters @PSBoundParameters
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Microsoft.Share...urationDatabase:) [Invoke-CimMethod], CimException
    + FullyQualifiedErrorId : Microsoft.SharePoint.PowerShell.SPCmdletConnectSPConfigurationDatabase,Microsoft.Mana 
   gement.Infrastructure.CimCmdlets.InvokeCimMethodCommand

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### Version and build of PowerShell the target node is running
Name                           Value                                                                                
----                           -----                                                                                
PSVersion                      5.1.17763.503                                                                        
PSEdition                      Desktop                                                                              
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                              
BuildVersion                   10.0.17763.503                                                                       
CLRVersion                     4.0.30319.42000                                                                      
WSManStackVersion              3.0                                                                                  
PSRemotingProtocolVersion      2.3                                                                                  
SerializationVersion           1.1.0.1

**Comment by ykuijs** [comment] 2019-06-12 18:28
This error is thrown inside of the Connect-SPConfigurationDatabase cmdlet. Do you use the PsDscRunAsCredential parameter in your config (Can you share your config) and does that user have the correct permissions in SQL? Does the server has proper access to the SQL server?

**Comment by ykuijs** [comment] 2019-07-03 18:07
@Harish9211 Any update?

**Comment by ykuijs** [comment] 2019-11-15 12:47
Closing this issue due to inactivity. Please reopen when still relevant and provide more information.

**Comment by EtsHere** [comment] 2020-02-26 09:02
SPFarm CreateSPFarm{
            # Kontod peavad olema SP Masinas Local Adminnid + SQL serveris SYSADMIN'id
            IsSingleInstance         = "Yes"
            Ensure                   = "Present"
            ServerRole               = "Custom"
            DatabaseServer           = $Node.SQLAlias
            FarmConfigDatabaseName   = $Node.FarmConfigDatabaseName
            AdminContentDatabaseName = $Node.AdminContentDatabaseName
            CentralAdministrationPort = 5000
            CentralAdministrationAuth = "NTLM"
            Passphrase               = $Passphrase
            FarmAccount              = $FarmAccount
            PsDscRunAsCredential     = $SPSetupAccount
            RunCentralAdmin          = $true
        }

[SPFarm]CreateSPFarm] Now joining to farm at server SP database SP19_Config
Value cannot be null.
Parameter name: service
    + CategoryInfo          : InvalidData: (Microsoft.Share...urationDatabase:) [], CimException
    + FullyQualifiedErrorId : Microsoft.SharePoint.PowerShell.SPCmdletConnectSPConfigurationDatabase

**Comment by EtsHere** [comment] 2020-02-26 10:17
Installed all SP and Win updates. Still same.

**Comment by considerITman** [comment] 2020-03-04 08:49
I'm getting the same error on a Windows Server 2016 with SharePoint 2019.
Updates are installed, Permissions to the DB are correct.
I'm configuring a different role (ApplicationWithSearch) but other than that, it's the same configuration as @EtsHere is using.

**Comment by ykuijs** [comment] 2020-03-05 13:11
Any events in the event log??

This article (about SP2010) is describing an issue with SQL aliases not being created, which result in event 5586 in application log: http://www.adventuresinsharepoint.co.uk/2013/10/10/failed-to-connect-to-the-configuration-database-when-adding-a-server-to-a-farm/

Is your SQL server behind a firewall or has the Windows Firewall enabled? Are you using a named instance?

**Comment by considerITman** [comment] 2020-03-06 07:25
I've read through the article and those are all things I tried already. It's indeed a named instance and there is an alias. I recreated the Alias (manually as well as per DSC) to make sure it's correct.
Connectivity to the SQL server _should_ not be the issue - the config database is created in the right place with the right permissions and the PSRunasCredentials are the same for the initial DB-creation as they are for the connection attempt. 

This is what the eventlog has to contribute:
`Log Name:      Microsoft-Windows-DSC/Operational
Source:        Microsoft-Windows-DSC
Date:          06.03.2020 08:18:01
Event ID:      4252
Task Category: None
Level:         Error
Keywords:      
User:          SYSTEM
Computer:      **********
Description:
Job {87F856E9-5F7A-11EA-A301-005056A5A5AD} : 
MIResult: 1
Error Message: Value cannot be null.
Parameter name: service
Message ID: Microsoft.SharePoint.PowerShell.SPCmdletConnectSPConfigurationDatabase
Error Category: 6
Error Code: 6
Error Type: MI
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-DSC" Guid="{50DF9E12-A8C4-4939-B281-47E1325BA63E}" />
    <EventID>4252</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x4000000000000000</Keywords>
    <TimeCreated SystemTime="2020-03-06T07:18:01.015882100Z" />
    <EventRecordID>388924</EventRecordID>
    <Correlation ActivityID="{1247F046-F23A-0001-300F-4C123AF2D501}" />
    <Execution ProcessID="5580" ThreadID="1692" />
    <Channel>Microsoft-Windows-DSC/Operational</Channel>
    <Computer>**********</Computer>
    <Security UserID="S-1-5-18" />
  </System>
  <EventData>
    <Data Name="JobId">{87F856E9-5F7A-11EA-A301-005056A5A5AD}</Data>
    <Data Name="MIResult">1</Data>
    <Data Name="ErrorMessage">Value cannot be null.
Parameter name: service</Data>
    <Data Name="MessageID">Microsoft.SharePoint.PowerShell.SPCmdletConnectSPConfigurationDatabase</Data>
    <Data Name="ErrorCategory">6</Data>
    <Data Name="ErrorCode">6</Data>
    <Data Name="ErrorType">MI</Data>
  </EventData>
</Event>
`

Other than that there are the expected messages about not being able to access the local farm in a later step.

**Comment by EtsHere** [comment] 2020-03-10 09:11
nothing in Event Viewer

**Comment by EtsHere** [comment] 2020-03-11 13:14
There are loads of these similar warnings, different DLL's:
Removal of an assembly from the global assembly cache failed:  C:\Program Files\Common Files\Microsoft Shared\Web Server Extensions\16\policy\Policy.15.0.Microsoft.SharePoint.Translation.dll Policy.15.0.Microsoft.SharePoint.Translation,Version=16.0.0.0

**Comment by EtsHere** [comment] 2020-03-13 07:17
Running:
New-SPConfigurationDatabase -DatabaseServer $DBServer -DatabaseName $DBConfig - $DBCAdmin -Passphrase $Passphrase -FarmCredentials $PSFarm -LocalServerRole Custom

New-SPCentralAdministration -Port "5000" -WindowsAuthProvider "NTLM" -Verbose

Works fine.

**Comment by ykuijs** [comment] 2020-03-13 20:00
Is this happening on all servers you are trying to join to the farm? Do you see anything in the ULS log?

@EtsHere The New-SPConfigurationDatabase will create a new ConfigDB. What happens if you try Connect-SPConfigurationDatabase?

**Comment by considerITman** [comment] 2020-03-18 08:47
I had to move to a manual installation for now, so sadly I won't be able to help with further narrowing that down.

**Comment by EtsHere** [comment] 2020-03-31 07:11
Tested only on one server. Had to continue with manual steps to get further.

**Comment by ykuijs** [comment] 2020-10-28 10:28
We need more information to reproduce/troubleshoot this issue, which unfortunately cannot be provided anymore. Closing this issue for now.

Please provide further details if you experience this issue as well. Make sure you use the most recent version of SharePointDsc and provide as much information as possible.

**Comment by VerdonTrigance** [comment] 2020-11-11 09:22
@ykuijs  Same problem here. Dunno what kind of information you may need more.

My config:

```
SPFarm CreateSPFarm
        {
            IsSingleInstance         = "Yes"
            Ensure                   = "Present"
            ServerRole               = "Custom"
            CentralAdministrationUrl = "http://dev-02"
            CentralAdministrationAuth = "NTLM"
            DatabaseServer           = $Node.DatabaseServer            
            FarmConfigDatabaseName   = "$($Node.DBPrefix)_Config"
            Passphrase               = $PassphraseCred
            FarmAccount              = $FarmAccount
            PsDscRunAsCredential     = $SPSetupAccount
            AdminContentDatabaseName = "$($Node.DBPrefix)_AdminContent"            
            RunCentralAdmin          = $true
            DependsOn                = "[SPInstall]InstallSharePoint"
        }
```

And here is log:

```
VERBOSE: [dev-02]: LCM:  [ Start  Resource ]  [[SPFarm]CreateSPFarm]
VERBOSE: [dev-02]: LCM:  [ Start  Test     ]  [[SPFarm]CreateSPFarm]
VERBOSE: [dev-02]:                            [[SPFarm]CreateSPFarm] Testing local SP Farm settings
VERBOSE: [dev-02]:                            [[SPFarm]CreateSPFarm] Getting the settings of the current local SharePoint Farm (if any)
VERBOSE: [dev-02]:                            [[SPFarm]CreateSPFarm] Detected installation of SharePoint 2019
VERBOSE: [dev-02]:                            [[SPFarm]CreateSPFarm] This node has never been connected to a farm
VERBOSE: [dev-02]:                            [[SPFarm]CreateSPFarm] Current Values: AdminContentDatabaseName=; ApplicationCredentialKey=; CentralAdministrationAuth=; CentralAdministrationPort=; CentralAdministrationUrl=; DatabaseServer=; Ensure=Absent; FarmAccount=; FarmConfigDatabaseName=; IsSingleInstance=Yes; Passphrase=; RunCentralAdmin=
VERBOSE: [dev-02]:                            [[SPFarm]CreateSPFarm] Target Values: AdminContentDatabaseName=dev02_AdminContent; CentralAdministrationAuth=NTLM; CentralAdministrationUrl=http://dev-02; DatabaseServer=dev-sql; Ensure=Present; FarmAccount=System.Management.Automation.PSCredential; FarmConfigDatabaseName=dev02_Config; IsSingleInstance=Yes; Passphrase=System.Management.Automation.PSCredential; RunCentralAdmin=True; ServerRole=Custom; Verbose=True
VERBOSE: [dev-02]:                            [[SPFarm]CreateSPFarm] Test-TargetResource returned False
VERBOSE: [dev-02]: LCM:  [ End    Test     ]  [[SPFarm]CreateSPFarm]  in 2.0790 seconds.
VERBOSE: [dev-02]: LCM:  [ Start  Set      ]  [[SPFarm]CreateSPFarm]
VERBOSE: [dev-02]:                            [[SPFarm]CreateSPFarm] Setting local SP Farm settings
VERBOSE: [dev-02]:                            [[SPFarm]CreateSPFarm] Getting the settings of the current local SharePoint Farm (if any)
VERBOSE: [dev-02]:                            [[SPFarm]CreateSPFarm] Detected installation of SharePoint 2019
VERBOSE: [dev-02]:                            [[SPFarm]CreateSPFarm] This node has never been connected to a farm
VERBOSE: [dev-02]:                            [[SPFarm]CreateSPFarm] Server not part of farm, creating or joining farm
VERBOSE: [dev-02]:                            [[SPFarm]CreateSPFarm] Executing as the local run as user dom\admin
VERBOSE: [dev-02]:                            [[SPFarm]CreateSPFarm] Importing function 'Add-SPDscConfigDBLock'.
VERBOSE: [dev-02]:                            [[SPFarm]CreateSPFarm] Importing function 'Get-SPDscConfigDBStatus'.
VERBOSE: [dev-02]:                            [[SPFarm]CreateSPFarm] Importing function 'Get-SPDscSQLInstanceStatus'.
VERBOSE: [dev-02]:                            [[SPFarm]CreateSPFarm] Importing function 'Remove-SPDscConfigDBLock'.
VERBOSE: [dev-02]:                            [[SPFarm]CreateSPFarm] $useSQLAuthentication is false or not specified; using default Windows authentication.
VERBOSE: [dev-02]:                            [[SPFarm]CreateSPFarm] Detected Version: SharePoint 2019 - configuring server as Custom
VERBOSE: [dev-02]:                            [[SPFarm]CreateSPFarm] The SharePoint config database 'dev02_Config' already exists, so this server will join the farm.
VERBOSE: [dev-02]:                            [[SPFarm]CreateSPFarm] The database exists, so attempt to join the server to the farm
VERBOSE: [dev-02]:                            [[SPFarm]CreateSPFarm] The server will attempt to join the farm now once every 60 seconds for the next 15 minutes.
VERBOSE: [dev-02]:                            [[SPFarm]CreateSPFarm] Leaving BeginProcessing Method of Connect-SPConfigurationDatabase.
VERBOSE: [dev-02]:                            [[SPFarm]CreateSPFarm] Entering function SPMountSPConfigurationDatabase.InternalProcessRecord
VERBOSE: [dev-02]:                            [[SPFarm]CreateSPFarm] Creating connection string for config db dev02_Config server dev-sql
VERBOSE: [dev-02]:                            [[SPFarm]CreateSPFarm] Creating connection string for admin content db admincontentdatabase server dev-sql
VERBOSE: [dev-02]:                            [[SPFarm]CreateSPFarm] Using NTLM for sql connection string
VERBOSE: [dev-02]:                            [[SPFarm]CreateSPFarm] Openning configdb so that I can join it at server dev-sql database dev02_Config in farm mode
VERBOSE: [dev-02]:                            [[SPFarm]CreateSPFarm] Now joining to farm at server dev-sql database dev02_Config
Value cannot be null.
Parameter name: service
    + CategoryInfo          : InvalidData: (Microsoft.Share...urationDatabase:) [], CimException
    + FullyQualifiedErrorId : Microsoft.SharePoint.PowerShell.SPCmdletConnectSPConfigurationDatabase
    + PSComputerName        : dev-02
 
VERBOSE: [dev-02]:                            [[SPFarm]CreateSPFarm] Leaving ProcessRecord Method of Connect-SPConfigurationDatabase.
VERBOSE: [dev-02]:                            [[SPFarm]CreateSPFarm] Leaving EndProcessing Method of Connect-SPConfigurationDatabase.
VERBOSE: [dev-02]:                            [[SPFarm]CreateSPFarm] Starting Install-SPHelpCollection
VERBOSE: [dev-02]:                            [[SPFarm]CreateSPFarm] Leaving BeginProcessing Method of Install-SPHelpCollection.
VERBOSE: [dev-02]: LCM:  [ End    Set      ]  [[SPFarm]CreateSPFarm]  in 68.6900 seconds.
PowerShell DSC resource MSFT_SPFarm  failed to execute Set-TargetResource functionality with error message: Cannot access the local farm. Verify that the local farm is properly configured, currently available, and
 that you have the appropriate permissions to access the database before trying again. 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : dev-02
```

Database created, permissions are fine. 
@EtsHere Hi, did you find the reason?

**Comment by ykuijs** [comment] 2020-11-11 10:22
Hi @VerdonTrigance, thanks for getting back to me. A few questions:

1. Does this happen every time/deployment?
1. What does your farm look like? Does this occur on every server in the farm?
1. Are you using precreated databases?
1. Can you share the ULS log?
1. I see you are using the Custom minrole. Does this also happen when you use a different minrole?
1. What patchlevel of SharePoint 2019 are you using? RTM or are you installing CUs before creating the farm?
1. What OS are you using?

**Comment by ykuijs** [comment] 2020-11-11 10:23
And what version of SharePointDsc are you using?

**Comment by VerdonTrigance** [comment] 2020-11-11 10:56
@ykuijs 
1. Every time
2. One server for everything except SQL + separate Sql Server
3. These databases was created by DSC previously, I just run config again.
4. 
[issues_1075.zip](https://github.com/dsccommunity/SharePointDsc/files/5523550/issues_1075.zip)


5. I didn't try different roles, because I don't want to change it later.
6. I'm not sure. That from license volume center without any CU.
7. Windows Server 2019 SE.
8. Version 4.3.0

**Comment by ykuijs** [comment] 2020-11-11 11:15
Ok, here some findings:
The server is trying to join the farm, because it detects that the specified database already exists. But since this the only server in the farm it makes more sense to create a new config database. Can you try to delete the database and try again?

Reason I ask: I have seen an issue with SP2019 before where the initial creation of the farm failed inside of SharePoint itself (nothing we can do about in SharePointDsc). This resulted in a config database being created, but no AdminContent database yet. The config database was however corrupted and could not be used to join new servers. The workaround for that situation was to delete the created config database and run the config again. Then the farm was created just fine.

Another thing I would like to to try as well is to install a recent CU before creating the farm. You can use SPProductUpdate for that:
```PowerShell
            SPInstall 'Install_SharePoint'
            {
                IsSingleInstance     = 'Yes'
                BinaryDir            = $installSPBinFolder
                ProductKey           = $ConfigurationData.NonNodeData.SharePoint.ProductKey
                InstallPath          = $ConfigurationData.NonNodeData.SharePoint.InstallPath
                DataPath             = $ConfigurationData.NonNodeData.SharePoint.DataPath
                PSDscRunAsCredential = $InstallAccount
                DependsOn            = '[SPInstallPrereqs]Install_SP_Prereqs'
            }

            SPProductUpdate 'LanguageDependant_CU'
            {
                SetupFile            = (Join-Path -Path $installSPCUFolder -ChildPath $ConfigurationData.NonNodeData.SharePoint.CULangFileName)
                ShutdownServices     = $false
                Ensure               = 'Present'
                PSDscRunAsCredential = $InstallAccount
                DependsOn            = '[SPInstall]Install_SharePoint'
            }

            SPProductUpdate 'Language_Independant_CU'
            {
                SetupFile            = (Join-Path -Path $installSPCUFolder -ChildPath $ConfigurationData.NonNodeData.SharePoint.CUFileName)
                ShutdownServices     = $false
                Ensure               = 'Present'
                PSDscRunAsCredential = $InstallAccount
                DependsOn            = '[SPProductUpdate]LanguageDependant_CU'
            }
```

**Comment by VerdonTrigance** [comment] 2020-11-11 12:04
@ykuijs 
After deleting databases:
[issue_1075_ps.txt](https://github.com/dsccommunity/SharePointDsc/files/5523830/issue_1075_ps.txt)
First Error means "User does not exist or not unique"

**Comment by ykuijs** [comment] 2020-11-12 16:31
Ok, so this issue is probably cause by the fact that the database isn't provisioned correctly during the first try. This leaves investigating why the error isn't very clear and why the database creation failed in the first place.

Can you share your full config?

**Comment by ykuijs** [comment] 2020-11-13 15:10
@VerdonTrigance Are you 100% sure all of the used accounts are in the domain\account format? The example you shared above unfortunately doesn't show this.

**Comment by VerdonTrigance** [comment] 2020-11-16 10:27
> @VerdonTrigance Are you 100% sure all of the used accounts are in the domain\account format? The example you shared above unfortunately doesn't show this.

Khm, some of them are not. I'll check it again.

**Comment by VerdonTrigance** [comment] 2020-11-17 09:06
I changed some properties of LCM to stop configuration after reboot and now I can't check what happening after installing Sharepoint:

```
Start-DscConfiguration -UseExisting -Verbose

Id     Name            PSJobTypeName   State         HasMoreData     Location             Command                  
--     ----            -------------   -----         -----------     --------             -------                  
1      Job1            Configuratio... Running       True            localhost            Start-DscConfiguration...
VERBOSE: Time taken for configuration job to complete is 0.1 seconds

```
How to show execution log as it was before?

**Comment by ykuijs** [comment] 2020-11-18 11:08
Do you mean the Central Administration application pool, which is created a timestamp in the name? That is a left over from leaving and rejoining a farm. During the leave process, the CA application pool isn't deleted. When you then rejoin the farm and SharePoint tries to create the application pool, it detects it already exist and adds the timestamp. To prevent this issue, recreate the farm (including databases) and make sure all websites and application pools are deleted in IIS.

This Install-SPService issue doesn't ring a bell. Can you please create a new issue and provide any debugging info (ULS or any other log)?

**Comment by VerdonTrigance** [comment] 2020-11-18 12:58
> Do you mean the Central Administration application pool, which is created a timestamp in the name? That is a left over from leaving and rejoining a farm. During the leave process, the CA application pool isn't deleted. When you then rejoin the farm and SharePoint tries to create the application pool, it detects it already exist and adds the timestamp. To prevent this issue, recreate the farm (including databases) and make sure all websites and application pools are deleted in IIS.
> 
> This Install-SPService issue doesn't ring a bell. Can you please create a new issue and provide any debugging info (ULS or any other log)?

Issue with app pool's account I resolved with cleaning everything out and deleting pools, dbs and others. restarting everything and beginning from the start. 
Issue with names of databases I open as another topic.

Now lets return to 'The type initializer for 'Microsoft.Office.Access.Services.BrandStrings' threw an exception.' error. It was years ago and still here. I faced with it when used AutoSPInstaller too. Case is simple - running Install-SPService from powershell leads to error above (and SPFarm resource call it), but running psconfig.exe looks like workaround for now.

**Comment by ykuijs** [comment] 2020-11-18 14:24
To my recollection, it is the first time I hear about this issue. Few questions:

- The last time you encountered the issue, was that with SP2019 as well?
- Do I it correctly understand that the issue also occurs when you run Install-SPService from a regular PowerShell console? In that case, it sounds like an issue in SharePoint itself and isn't related to SharePointDsc. Creating a regular support case would be best to get to the bottom of this.

**Comment by VerdonTrigance** [comment] 2020-11-18 14:45
> To my recollection, it is the first time I hear about this issue. Few questions:
> 
> * The last time you encountered the issue, was that with SP2019 as well?
> * Do I it correctly understand that the issue also occurs when you run Install-SPService from a regular PowerShell console? In that case, it sounds like an issue in SharePoint itself and isn't related to SharePointDsc. Creating a regular support case would be best to get to the bottom of this.

I'm not sure, but it may be related to 2013 farms too. (it was really years ago...)
Answer to second question is 'yes' it happens with regular powershell, not DSC.

**Comment by ykuijs** [comment] 2020-11-18 14:57
Ok, in that case creating a support case with Microsoft Support would be your best option. They have access to the SharePoint source code and therefore can troubleshoot and fix this issue much better than we can.

**Comment by ykuijs** [comment] 2020-11-25 15:10
Back to the original issue: This was caused by not using credentials in domain\user format. Closing this issue now.

@VerdonTrigance For the other issue: If you are able to reproduce the issue, please contact Microsoft support to have it investigated and possibly fixed.

**Closed by ykuijs** 2020-11-25 15:10 UTC
Labels: needs investigation, needs more information
