### ISSUE TITLE
PSDSCRunasCredentials implementation

### ISSUE THREAD

**Issue by vshupak** [dsccommunity/SharePointDsc#1278] opened 2021-01-18 11:43 UTC
Hi everyone,

I am trying to get DSC to work in an environment, where only the HTTPS endpoint is available. I am using the **SPFarm** resource for the testing. With **PSDSCRunasCredentials**, I am getting _access denied_. (SharePoint 2019, Windows Server 2019)
I am creating a _CIMSession_, for the **start-dscconfiguration** cmdlet, if you were wondering.
I tried with all kinds of authentication for the CIMSession, but it does not change a thing. I need to understand how is  _PSDSCRunasCredentials_ working. Is there any place I can see it? (could not find it in the SharePointDSC modules)

**Comment by ykuijs** [comment] 2021-01-20 12:37
Hi @vshupak, not sure why there is a difference between using InstallAccount and PSDscRunAsCredential.

The InstallAccount parameter we had to implement for PowerShell v4 because that ran the LCM as the System account by default and there was no way to change that. With the InstallAccount parameter DSC is using the System account to run the LCM on the target server under and then SharePointDsc uses PowerShell Remoting and CredSSP to have the target server to connect to itself as the desired user (and escape out of the System context).

PowerShell v5 intoduced the PSDscRunAsCredential parameter, which is a PowerShell DSC generic parameter. That is why you can't find any implementation in SharePointDsc. With this parameter, DSC is using the specified account to run the LCM on the target server under. So we don't have to escape the System context there.

Can you share the cmdlets you are running and the error messages you are getting?

**Comment by vshupak** [comment] 2021-01-28 07:31
Hi @ykuijs !
From what I can see, due to some special security hardening, it is not working. Even if it is a PowerShell DSC generic parameter, do you know how it is running? is it a start-process or how does it actually work?
For example the simple installation process for the sample config (shortened) fails with access denied:
`        File SharePointBinaries
        {
            Ensure = "Present"  
            Type = "Directory"
            DestinationPath = “Destination Path”
            SourcePath = “Source Path”
            Recurse = $true
            Checksum = "modifiedDate"
            PsDscRunAsCredential = $node.installAccount
        }


Start-DscConfiguration -Path Prerequisites -Wait -Force -Verbose -ErrorAction Stop -CimSession $session
`
The error itself is like this:

> VERBOSE: [ServerName]: LCM:  [ End    Test     ]  [[SPInstall]InstallSharePoint]  in 2.1280 seconds.
Connecting to remote server localhost failed with the following error message : Access is denied. For more information, see the about_Remote_Troubleshooting Help topic.
At line:1 char:1
+ Start-DscConfiguration -CimSession $session -Path NodeConfiguration - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (:) [], CimException
    + FullyQualifiedErrorId : RemoteRunspaceCreationFailed
    + PSComputerName        : server.domain.com

**Comment by ykuijs** [comment] 2021-01-28 20:32
With PsDscRunAsCredential, DSC starts the remote process as the specified account. This is all done under the hood.

Few questions:
- I see that you specified $node.InstallAccount as PSDscRunAsCredential. Is this variable a PSCredential object?
- Why aren't you using the -ComputerName parameter? Is there a special reason for using a CIM session?
- How are you creating the CIM session? Do you have some example code?

**Comment by ykuijs** [comment] 2021-01-28 22:00
Perfect, just checking ;-)

I will see if I can reproduce the issue on my environment.

**Comment by ykuijs** [comment] 2021-02-04 16:11
@vshupak I was able to reproduce the issue. Now investigating the root cause

**Comment by ykuijs** [comment] 2021-02-04 19:37
Looks like this isn't specific to SharePointDsc. Found this issue in dsccommunity/ActiveDirectoryDsc#128 which is describing the same issue.

**Comment by vshupak** [comment] 2021-02-05 06:56
@ykuijs, well that is bad news for me I guess... :/ since it was not fixed since 2016, when it appeared in the backlog.
Does this mean that all datacenters, including Microsoft's are just using the HTTP listener? Maybe there is a solution out there...

**Comment by ykuijs** [comment] 2021-02-05 07:49
Even though PowerShell is using an HTTP listener, this does not mean the traffic send across that connection is unencrypted. PowerShell itself encrypts all the commands before sending it to the remote server via HTTP. If you configure HTTPS, you basically add an extra encryption layer on top of the default PowerShell encryption.

Quote:

> **Encryption and transport protocols**
It is helpful to consider the security of a PowerShell Remoting connection from two perspectives: initial authentication, and ongoing communication. Regardless of the transport protocol used (HTTP or HTTPS), WinRM **always encrypts** all PowerShell remoting communication after initial authentication.

Source: https://docs.microsoft.com/en-us/powershell/scripting/learn/remoting/winrmsecurity#encryption-and-transport-protocols

**Comment by vshupak** [comment] 2021-02-05 08:01
> 
> 
> Even though PowerShell is using an HTTP listener, this does not mean the traffic send across that connection is unencrypted. PowerShell itself encrypts all the commands before sending it to the remote server via HTTP. If you configure HTTPS, you basically add an extra encryption layer on top of the default PowerShell encryption.
> 
> Quote:
> 
> > **Encryption and transport protocols**
> > It is helpful to consider the security of a PowerShell Remoting connection from two perspectives: initial authentication, and ongoing communication. Regardless of the transport protocol used (HTTP or HTTPS), WinRM **always encrypts** all PowerShell remoting communication after initial authentication.
> 
> Source: https://docs.microsoft.com/en-us/powershell/scripting/learn/remoting/winrmsecurity#encryption-and-transport-protocols

Yes, that is correct and indeed valid, however it is a mandatory security hardening guideline for my client to only have the HTTPS listener. I still think it could be resolved by granting some permissions somewhere. Maybe local system needs some privileges? I checked with procmon, but strangely find no access denied entries....

**Comment by ykuijs** [comment] 2021-02-05 08:56
Hi @vshupak I have discussed this issue with some others in the DSC Community and it looks like nobody has a solution at the moment. One suggested to allow HTTP listeners and block traffic to that port from the outside via the firewall. That way the HTTP listener is only available for the server itself. This does mean you need to use a pull scenario.

Another option would be to create a support case to have this investigated by the PowerShell Product Group. They can tell you if it is supported (and if so how to do it) or not. Would this be a possibility for you?

**Comment by ykuijs** [comment] 2021-02-05 09:39
Did some further testing:
You mentioned that the built-in File resource worked as expected and I was able to confirm this. The File resource is a binary resource.

The built-in Archive resource has the same Access Denied issue. That resource is a PowerShell resource like the SharePointDsc resources.

So it looks like the issue occurs with all PowerShell resources.

**Comment by vshupak** [comment] 2021-02-24 10:18
We opened a case with Microsoft to investigate this issue.

**Comment by ykuijs** [comment] 2021-06-04 10:46
The support case revealed that DSC tries to connect to the localhost over HTTP. Since the HTTP listener was removed, this did not work.

A workaround is **not** delete the HTTP listener, but add a firewall rule to block external traffic to port 5985. That way DSC is still able to use the HTTP listener without allowing others to use the HTTP protocol.

**NOTE:** As mentioned earlier: PowerShell Remoting already encrypts the traffic by default. So if you want traffic to be encrypted, that is already the case and there is no specific need to switch to an HTTPS listener.

Closing this issue, since we can't fix this issue in SharePointDsc

**Closed by ykuijs** 2021-06-04 10:46 UTC
Labels: on hold, waiting for author response
