### ISSUE TITLE
SPSearchTopology: Export places the $ConfigurationData between quotes

### ISSUE THREAD

**Issue by JenTonUg** [dsccommunity/SharePointDsc#1381] opened 2022-02-16 15:49 UTC
I'm looking for some help, because I'm having a hard time getting SPSearchTopology configured. I keep getting the following events in the DSC Log, currently with exactly one minute in between:

> Job {3FF2D5A4-8F36-11EC-B34D-EE000000024D} : 
> This event indicates that a non-terminating error was thrown when DSCEngine was executing Set-TargetResource on MSFT_SPSearchTopology DSC resource. FullyQualifiedErrorId is Microsoft.Office.Server.Search.Cmdlet.GetSearchServiceInstance. Error Message is SearchServiceInstance is not found on server 'System.MyDomain.com'..

And

> Job {3FF2D5A4-8F36-11EC-B34D-EE000000024D} : 
> MIResult: 1
> Error Message: SearchServiceInstance is not found on server 'System.MyDomain.com'.
> Message ID: Microsoft.Office.Server.Search.Cmdlet.GetSearchServiceInstance
> Error Category: 6
> Error Code: 6
> Error Type: MI

My config for the main server (APPSERVER01) performing the install:

```
SPSearchServiceApp CreateSearchServiceApplication {
	AlertsEnabled               = $True;
	ApplicationPool             = "SharePoint Web Services Default";
	DatabaseName                = Farm_SA_Search";
	DatabaseServer              = "sql01.mydomain.com"
	Ensure                      = "Present";
	FixFarmAccountPermissions   = $True;
	Name                        = "Search Service Application";
	ProxyName                   = "Search Service Application Proxy";
	PsDscRunAsCredential        = $SPSetupAccount;
	SearchCenterUrl             = "https://farm.mydomain.com/sites/search/Pages";
	DependsOn                   = @("[SPManagedAccount]SPCrawlAccount","[SPWebApplication]SharePointMySites","[SPWebApplication]SharePointSites","[SPServiceAppPool]SharePointWebServicesDefault","[WaitForAll]AppServersReadyForSearchTopology")
}
SPSearchTopology CreateSearchTopology {
	ServiceAppName          = "Search Service Application";
	Admin                   = @("APPSERVER01","APPSERVER02","APPSERVER03");
	Crawler                 = @("APPSERVER01","APPSERVER02","APPSERVER03");
	ContentProcessing       = @("APPSERVER01","APPSERVER02","APPSERVER03");
	AnalyticsProcessing     = @("APPSERVER01","APPSERVER02","APPSERVER03");
	QueryProcessing         = @("APPSERVER01","APPSERVER02","APPSERVER03");
	IndexPartition          = @("APPSERVER01","APPSERVER02","APPSERVER03");
	PsDscRunAsCredential    = $SPSetupAccount;
	FirstPartitionDirectory = "E:\SearchIndex\0";
 	DependsOn               = "[SPSearchServiceApp]CreateSearchServiceApplication"
}
```

The other two servers (02 and 03) are at that moment in an installed state, and joined to the farm. Further configuration is not yet performed, and they are waiting to be added to the topology. 
Output of Get-SPEnterpriseSearchServiceInstance shows the search instances on those servers as online.
I've been pulling my hair for over a week on this, I've no idea where this "system" is coming from. What am I doing wrong, because I'm definitely doing something wrong.

**Comment by ykuijs** [comment] 2022-02-17 12:10
Hi @JenTonUg, I have a few questions:

- Do you have some verbose logging you can share?
- Is "System" really the value that is being returned or did you update this to prevent sharing server names?
- Which version of SharePointDsc are you using?

**Comment by JenTonUg** [comment] 2022-02-17 13:15
Hi @ykuijs, 
Thank you for getting back to me. so quickly! 

- I do, you can find it on [pastebin](https://pastebin.com/eYgTUDEM). I've switched out usernames, domain and servernames with a replace all, so it should be consistent across the board with my initial post.
- When I mention "system.mydomain.com" only the "mydomain.com" part is switched to hide server names. System is there in the log.
- I'm using SharepointDSC 5.0.0.

Let me know if I can provide you with any further information.

**Comment by ykuijs** [comment] 2022-02-17 14:01
Hi @JenTonUg,

I think something is going wrong with your config. When reviewing your logging I noticed this:

>  {"time": "2022-02-17T12:16:55.820+01:00", "type": "verbose", "message": "[APPSERVER01]:                            [[SPSearchTopology]CreateSearchTopology] Current Values: Admin=(); AnalyticsProcessing=(); ContentProcessing=(); Crawler=(); FirstPartitionDirectory=C:\\Program Files\\Microsoft Office Servers\\16.0\\Data\\Office Server\\Applications; IndexPartition=(); QueryProcessing=(); ServiceAppName=Search Service Application"},
>  {"time": "2022-02-17T12:16:55.820+01:00", "type": "verbose", "message": "[APPSERVER01]:                            [[SPSearchTopology]CreateSearchTopology] Target Values: Admin=(**System.Collections.Hashtable.NonNodeData.SearchAdminServers**); AnalyticsProcessing=(**System.Collections.Hashtable.NonNodeData.SearchAnalyticsProcessingServers**); ContentProcessing=(**System.Collections.Hashtable.NonNodeData.SearchContentProcessingServers**); Crawler=(**System.Collections.Hashtable.NonNodeData.SearchCrawlerServers**); FirstPartitionDirectory=E:\\SearchIndex\\0; IndexPartition=(**System.Collections.Hashtable.NonNodeData.SearchIndexPartitionServers**); QueryProcessing=(**System.Collections.Hashtable.NonNodeData.QueryProcessingServers**); ServiceAppName=Search Service Application; Verbose=True"},

This is where the System is coming from. This must be caused by the way the MOF file is compiled. Can you share your exact configuration of the SPSearchTopology resource?

**Comment by JenTonUg** [comment] 2022-02-17 14:08
Certainly, could I contact you directly?

**Comment by IlleNilsson** [comment] 2022-02-17 14:20
I’m an idot to.

For a long time i tought that NonNodeData was required, it is not. You can name the NonNodeData whatever you want. And you can have multiple ‘NonNodeData’

**Comment by IlleNilsson** [comment] 2022-02-17 14:26
To clarify my new knowledge, being less of an idot.

@{
    AllNodes = @(
        @{
            NodeName = 'localhost'
            NodeType = 'Client' # VALUES: Client | Server
            NodeRole = @('BizTalk', 'ServiceFabric', 'SqlServer') # VALUES: BizTalk & ServiceFabric & SqlServer
            BizTalkReplica = 'Primary' # VALUES: Primary | Secondary
            ServiceFabricReplica = 'Primary' # VALUES: Primary | Secondary
            SqlServerReplica = 'Primary' # VALUES: Primary | Secondary
            PSDscAllowDomainUser = $true
            PSDscAllowPlainTextPassword = $true
        },
        @{
            NodeName = '*'
        }
    )
    Modules = @(
        @{ Name = 'xPSDesiredStateConfiguration'; Version = '9.1.0' }
        @{ Name = 'ComputerManagementDsc'; Version = '8.5.0' }
        @{ Name = 'NetworkingDsc'; Version = '8.2.0' }
        @{ Name = 'xWindowsUpdate'; Version = '2.8.0' }
    )
    BizTalk = @{
        Modules = @(
            @{ Name = 'BizTalkServer'; Version = '0.1.1.4' }
        )
        ProductName = 'Microsoft BizTalk Server 2020'
        ProductId = '{205F5836-7512-4A06-9E74-ADC8AFA0EEC5}'
        SourcePath = 'C:\Users\Public\Public Media\BizTalk 2020\BizTalk Server\Setup.exe'
        Patch = @{
            ProductName = 'Microsoft BizTalk Server 2020 Cumulative Update 3 [KB 5007969]'
            ProductId = '{0AA5B03E-C72E-4769-B351-97C57E24BF5A}'
            SourcePath = 'C:\Users\Public\Public Media\BizTalk 2020\BizTalk Server CUs\BTS2020-KB5007969-ENU (CU3).exe'
        }
        # TODO: Break out to psd1 file
        Adapters = @(
            @{ Name = 'AzureBlobStorage'
                ReceiveHandlers = @(
                    @{ Host = 'GcRxHost64' }
                )
                SendHandlers = @(
                    @{ Host = 'GcSxHost64'; Default = $false }
                )
            }
        )
        Hosts = @()
    }
    ServiceFabric = @{
        Modules = @(
            @{ Name = 'ServiceFabricDsc'; Version = '1.0.0.1' }
        )
        ProductName = '???'
        ProductId = '???'
        SourcePath = '\\???\???'
        # TODO: Break out to psd1 file
    }
    SqlServer = @{
        Modules = @(
            @{ Name = 'xFailoverCluster'; Version = '1.16.0' } # TODO: There is a version 1.17.0 that enables placing cluster nodes in desired AD OU, need som OS love
            @{ Name = 'SqlServerDsc'; Version = '15.2.0' }
        )
        SourcePath = 'C:\Users\Public\Public Media\SQL Server 2019'
        # TODO: Break out to psd1 file
        ConfigureWindowsFirewall = $true
        SQLUserDBDir = $null
        SQLUserDBLogDir = $null
        SQLTempDBDir = $null
        SQLTempDBLogDir = $null
        FailoverClusterName = 'CLUSQL'
        FailoverClusterIPAddress = '192.168.1.200'
        FailoverClusterIgnoreNetwork = '10.0.3.0/16'
        SqlInstances = @(
            @{
                Name = 'MSSQLSERVER'
                Features = 'SQLENGINE'
                AsServerMode = 'TABULAR'
                MaxDop = 0
                TcpPort = 1433
                EndPointIPAddress = $null
                EndPointPort = $null
                Logins = @();
            }
        )
    }
    Windows = @{
        SourcePath = 'C:\Users\Public\Public Media\Windows 10\Sources\Sxs'
    }
}



From: Ilian Nilsson
Sent: Thursday, 17 February 2022 15:20
To: dsccommunity/SharePointDsc ***@***.***>; dsccommunity/SharePointDsc ***@***.***>
Cc: Subscribed ***@***.***>
Subject: RE: [dsccommunity/SharePointDsc] SPSearchTopology: "SearchServiceInstance is not found on server "System.MyDomain.com" (Issue #1381)

I’m an idot to.

For a long time i tought that NonNodeData was required, it is not. You can name the NonNodeData whatever you want. And you can have multiple ‘NonNodeData’

**Comment by ykuijs** [comment] 2022-02-17 14:28
@JenTonUg, those damn quotes.....been there, done that 😛 Sometimes having a fresh pair of eye will do magic. Let me know if this fixes the issue!

@IlleNilsson, absolutely! I thought that as well in the beginning. But just AllNodes is a fixed name, NoneNodeData indeed isn't......you can name it whatever you want!

**Comment by IlleNilsson** [comment] 2022-02-17 14:29
And if you are wondering about the Module sections, here is how we distribute them on nodes

#Requires -PSEdition Desktop
#Requires -Version 5.1
#Requires -RunAsAdministrator

#Requires -Modules @{ ModuleName = 'Microsoft.PowerShell.SecretManagement'; ModuleVersion = '1.1.2' }
#Requires -Modules @{ ModuleName = 'Microsoft.PowerShell.SecretStore'; ModuleVersion = '1.0.6' }

function Enable-Dsc {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true)]
        [hashtable]$Node,
        [string[]]$NodeRole
    )

    $ErrorActionPreference = 'Stop'
    Set-ExecutionPolicy -ExecutionPolicy RemoteSigned
    Get-Job | Remove-Job -Force # INFO: Remove any previous jobs

    # INFO: Retreive DSC resources needed for all nodes for all roles
    $commonModules = $Node.Modules

    $Node.AllNodes | # INFO: Filter which nodes should be used by role
        Where-Object { ($_.NodeName -ne '*') -and
            (($null -eq $NodeRole) -or (Compare-Object $NodeRole $_.NodeRole -ExcludeDiff)) } |
                ForEach-Object {
        $combinedModules = $commonModules

        $_.NodeRole | # INFO: Filter which roles should be used for current node
            Where-Object { ($null -eq $NodeRole) -or (Compare-Object $_ $NodeRole -ExcludeDiff) } |
                ForEach-Object {
            # INFO: Retreive DSC resources for current node and current role
            $roleModules = Invoke-Expression "`$Node.$_.Modules"
            # INFO: Add DSC resources for role to combined resource modules
            $combinedModules += $roleModules
        }

        Write-Progress -Activity 'Preparing nodes for DSC' -Status "Node: $($_.NodeName)"

        try { # INFO: Install PowerShell modules on nodes # NOTE: This is executed on remote node, it's hard to debug so be carefull
            Invoke-Command -Computer $_.NodeName -Script {
                param([array]$modules)

                #Requires -Version 5.1
                #Requires -RunAsAdministrator

                [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
                $ErrorActionPreference = 'Stop'
                Set-ExecutionPolicy -ExecutionPolicy RemoteSigned
                Set-Item -Path 'WSMan:\localhost\MaxEnvelopeSizeKb' -Value 8192

                if (!(Get-PackageProvider -Name 'NuGet')) { # INFO: Install NuGet package provider if not present
                    Install-PackageProvider -Name 'NuGet' -Scope AllUsers -Confirm:$false -Force | Out-Null
                }

                if (($psGalleryRepo = Get-PSRepository -Name 'PSGallery') -and
                    $psGalleryRepo.InstallationPolicy -ne 'Trusted') { # INFO: Set PSGallery installation policy to trusted if it isn't
                    Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
                }

                $modules | Where-Object { $null -ne $_ } | Where-Object { # INFO: Install PowerShell modules not present on node
                    param(
                        [string]$RequiredVersion = $_.Version
                    )

                    !(Get-Module -Name $_.Name -ListAvailable | Where-Object { $_.Version -eq $RequiredVersion } )
                } | ForEach-Object {
                    Find-Module -Name $_.Name -RequiredVersion $_.Version |
                        Install-Module -Scope AllUsers -AllowClobber
                }
            } -Argument (, $combinedModules) -AsJob -EnableNetwork
        } catch {
            Complete-Job

            throw
        }
    }

    Complete-Job

    Write-Progress -Activity 'Preparing nodes for DSC' -Status "Done"
}

function Complete-Job {
    [CmdletBinding()]
    param()

    try {
        Get-Job | Wait-Job; Get-Job | Receive-Job
        Get-Job | Remove-Job
    } catch {
        Get-Job | Receive-Job

        throw
    } finally {
        Get-Job | Remove-Job -Force
    }
}

function Get-StreamPath {
    [CmdletBinding()]
    param()

    "$((Get-Item .).Parent.Name)\$((Get-Item .).Name)"
}

function New-Secret {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [ValidateNotNullOrEmpty()]
        [string]$Account,
        [string]$Secret
    )

    (New-Object System.Management.Automation.PsCredential(
        $Account, (ConvertTo-SecureString $Secret -AsPlainText -Force)))
}


From: Ilian Nilsson
Sent: Thursday, 17 February 2022 15:26
To: dsccommunity/SharePointDsc ***@***.***>; dsccommunity/SharePointDsc ***@***.***>
Cc: Subscribed ***@***.***>
Subject: RE: [dsccommunity/SharePointDsc] SPSearchTopology: "SearchServiceInstance is not found on server "System.MyDomain.com" (Issue #1381)

To clarify my new knowledge, being less of an idot.

@{
    AllNodes = @(
        @{
            NodeName = 'localhost'
            NodeType = 'Client' # VALUES: Client | Server
            NodeRole = @('BizTalk', 'ServiceFabric', 'SqlServer') # VALUES: BizTalk & ServiceFabric & SqlServer
            BizTalkReplica = 'Primary' # VALUES: Primary | Secondary
            ServiceFabricReplica = 'Primary' # VALUES: Primary | Secondary
            SqlServerReplica = 'Primary' # VALUES: Primary | Secondary
            PSDscAllowDomainUser = $true
            PSDscAllowPlainTextPassword = $true
        },
        @{
            NodeName = '*'
        }
    )
    Modules = @(
        @{ Name = 'xPSDesiredStateConfiguration'; Version = '9.1.0' }
        @{ Name = 'ComputerManagementDsc'; Version = '8.5.0' }
        @{ Name = 'NetworkingDsc'; Version = '8.2.0' }
        @{ Name = 'xWindowsUpdate'; Version = '2.8.0' }
    )
    BizTalk = @{
        Modules = @(
            @{ Name = 'BizTalkServer'; Version = '0.1.1.4' }
        )
        ProductName = 'Microsoft BizTalk Server 2020'
        ProductId = '{205F5836-7512-4A06-9E74-ADC8AFA0EEC5}'
        SourcePath = 'C:\Users\Public\Public Media\BizTalk 2020\BizTalk Server\Setup.exe'
        Patch = @{
            ProductName = 'Microsoft BizTalk Server 2020 Cumulative Update 3 [KB 5007969]'
            ProductId = '{0AA5B03E-C72E-4769-B351-97C57E24BF5A}'
            SourcePath = 'C:\Users\Public\Public Media\BizTalk 2020\BizTalk Server CUs\BTS2020-KB5007969-ENU (CU3).exe'
        }
        # TODO: Break out to psd1 file
        Adapters = @(
            @{ Name = 'AzureBlobStorage'
                ReceiveHandlers = @(
                    @{ Host = 'GcRxHost64' }
                )
                SendHandlers = @(
                    @{ Host = 'GcSxHost64'; Default = $false }
                )
            }
        )
        Hosts = @()
    }
    ServiceFabric = @{
        Modules = @(
            @{ Name = 'ServiceFabricDsc'; Version = '1.0.0.1' }
        )
        ProductName = '???'
        ProductId = '???'
        SourcePath = '\\???\???'
        # TODO: Break out to psd1 file
    }
    SqlServer = @{
        Modules = @(
            @{ Name = 'xFailoverCluster'; Version = '1.16.0' } # TODO: There is a version 1.17.0 that enables placing cluster nodes in desired AD OU, need som OS love
            @{ Name = 'SqlServerDsc'; Version = '15.2.0' }
        )
        SourcePath = 'C:\Users\Public\Public Media\SQL Server 2019'
        # TODO: Break out to psd1 file
        ConfigureWindowsFirewall = $true
        SQLUserDBDir = $null
        SQLUserDBLogDir = $null
        SQLTempDBDir = $null
        SQLTempDBLogDir = $null
        FailoverClusterName = 'CLUSQL'
        FailoverClusterIPAddress = '192.168.1.200'
        FailoverClusterIgnoreNetwork = '10.0.3.0/16'
        SqlInstances = @(
            @{
                Name = 'MSSQLSERVER'
                Features = 'SQLENGINE'
                AsServerMode = 'TABULAR'
                MaxDop = 0
                TcpPort = 1433
                EndPointIPAddress = $null
                EndPointPort = $null
                Logins = @();
            }
        )
    }
    Windows = @{
        SourcePath = 'C:\Users\Public\Public Media\Windows 10\Sources\Sxs'
    }
}



From: Ilian Nilsson
Sent: Thursday, 17 February 2022 15:20
To: dsccommunity/SharePointDsc ***@***.******@***.***>>; dsccommunity/SharePointDsc ***@***.******@***.***>>
Cc: Subscribed ***@***.******@***.***>>
Subject: RE: [dsccommunity/SharePointDsc] SPSearchTopology: "SearchServiceInstance is not found on server "System.MyDomain.com" (Issue #1381)

I’m an idot to.

For a long time i tought that NonNodeData was required, it is not. You can name the NonNodeData whatever you want. And you can have multiple ‘NonNodeData’

**Comment by JenTonUg** [comment] 2022-02-17 15:37
Good news, it worked, and I have more information to report. I started off with a reverseDSC config at first. I noticed that the quotes are in there too. I've tried it again, to make certain that the quotes over there are generated by reverseDSC and the result is consistent!
![image](https://user-images.githubusercontent.com/94599813/154507202-b418fe99-7784-4c6a-917b-555747965cfe.png)

I now get a new error "Could not connect to the HostController service on server <servername> Topology Activation could not be started for constellation 0B8D89", but I should be able to fix this myself. Thank you for all the help!

**Comment by ykuijs** [comment] 2022-02-17 15:42
Thanks for letting me know! I will check and correct the export function to make sure this is exported correctly!

**Comment by ykuijs** [comment] 2022-02-17 15:48
You are absolutely correct, the quotes are indeed added by mistake. Have implemented a fix, which will be included in my bugfix PR!

**Comment by JenTonUg** [comment] 2022-02-18 09:22
Looks like I closed this early before you had the chance to commit your fix.

**Comment by ykuijs** [comment] 2022-02-22 20:07
Perfect, have fixed the SPSearchIndexPartition resource as well!

**Closed** 2022-02-23 20:59 UTC
Labels: bug, in progress
