### ISSUE TITLE
Naming not matching module name: 

### ISSUE THREAD

**Issue by wmaniek123** [dsccommunity/SharePointDsc#1290] opened 2021-02-16 15:01 UTC
SharePoint**Dsc** module is created inside SharePoint**DSC** folders. This is not problem for Windows at all but when integrating with Puppet Ansible etc the case sensitivity is important. It happens when I use install-module and save-module cmdlet's. Thanks

**Comment by ykuijs** [comment] 2021-02-20 20:14
I believe this is caused by the fact that the psd1 file has the name SharePointDsc, but the module is called SharePointDSC in the PowerShell Gallery. Have to see if it is possible to update the latter.

**Comment by ykuijs** [comment] 2021-03-04 13:21
@wmaniek123 Can you tell me a little more about the scenario you are implementing and when the error message you are getting (screenshot if possible)?

**Comment by ykuijs** [comment] 2021-03-17 09:45
@wmaniek123 Any update?

**Comment by wmaniek123** [comment] 2021-04-06 12:06
I guess it is not a problem for windows implementation. The module folder is displaying with capital 'DSC' at the end. We corrected our custom puppet code and this is not an issue for us anymore
![image](https://user-images.githubusercontent.com/44258277/113708129-23f50400-96e1-11eb-820e-8d6baa4e00cf.png)

**Comment by ykuijs** [comment] 2021-04-08 21:33
The Windows file system isn't case sensitive indeed, so this isn't a problem there. The issue is that inside of the code, we named everything SharePointDsc, but the module is called SharePointDSC in the PowerShell Gallery. That is why during installation, the folder is named SharePointDSC and you run into the issue.

Good to know this is no longer an issue. Closing this issue now

**Closed by ykuijs** 2021-04-08 21:33 UTC
Labels: not fixed
