### ISSUE TITLE
SPSearchResultSource doesn't allow an empty ScopeUrl

### ISSUE THREAD

**Issue by rurikon** [dsccommunity/SharePointDsc#1268] opened 2020-12-02 13:27 UTC
#### Details of the scenario you tried and the problem that is occurring

https://github.com/dsccommunity/SharePointDsc/wiki/SPSearchResultSource instructs that if you want to set a global result source, you should leave ScopeUrl empty. However, setting an empty string will result in an error saying it's not allowed, and leaving the parameter out will say it's required. But it looks like setting ScopeUrl to the Central Administration url makes the result source global.

#### Verbose logs showing the problem

When setting ScopeUrl = "" and running Test-DscConfiguration:

```powershell
PowerShell DSC resource MSFT_SPSearchResultSource  failed to execute Test-TargetResource functionality with error message: Cannot bind argument to parameter 'ScopeUrl' because it is an empty string.
    + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : xxxxxxxx
```

When leaving the parameter out and trying to build mof files:

```powershell
Resource 'SPSearchResultSource' requires that a value of type 'String' be provided for property 'ScopeUrl'.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : MissingValueForMandatoryProperty
```

When setting the Central Administration url as the ScopeUrl, it looks like the result source is set as global.

#### Suggested solution to the issue

Verify that my assuption above is correct and update documentation.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

As suggested by documentation, but resulting in an error:

```powershell
SPSearchResultSource Intranet
{
	Name			= "Intranet"
	ScopeName		= "SSA"
	ScopeUrl		= ""
	SearchServiceAppName	= "Search Service Application"
	Query			= '{searchTerms}'
	ProviderType		= "Local SharePoint Provider"
	Ensure			= "Present"
	PsDscRunAsCredential	= $SetupAccount
	DependsOn		= "[SPSearchServiceApp]SearchServiceApp"
}
```

This seems to work:

```powershell
SPSearchResultSource Intranet
{
	Name			= "Intranet"
	ScopeName		= "SSA"
	ScopeUrl		= "https://central-admin"
	SearchServiceAppName	= "Search Service Application"
	Query			= '{searchTerms}'
	ProviderType		= "Local SharePoint Provider"
	Ensure			= "Present"
	PsDscRunAsCredential	= $SetupAccount
	DependsOn		= "[SPSearchServiceApp]SearchServiceApp"
}
```

#### The operating system the target node is running

I don't think this is relevant to the issue.

#### Version of SharePoint that is used (e.g. SharePoint 2016)

SharePoint 2019

#### Version and build of PowerShell the target node is running

5.1.17763.1490

#### Version of the DSC module that was used

4.3.0

**Comment by ykuijs** [comment] 2020-12-03 16:34
Hi @rurikon Thanks for reporting the issue. I have been able to reproduce the issue and now looking for a solution.

**Comment by ykuijs** [comment] 2020-12-03 16:45
@rurikon I just looked at the code and if I am not mistaking, if you specify ScopeName = "SSA" it doesn't matter what you enter as value for the ScopeUrl parameter. Are you able to confirm?

**Comment by rurikon** [comment] 2020-12-11 12:31
I put some random strings as ScopeUrl and none of them gave errors. So it looks like it's working.

**Comment by ykuijs** [comment] 2021-02-05 11:52
Since the ScopeUrl is a Key parameter, it cannot be empty or not specified. I have updated the Readme so that the documentation explains the use of the SSA ScopeName in a better way.

**Comment by ykuijs** [comment] 2021-02-05 11:56
Changes will be included in my next PR

**Closed** 2021-03-24 20:50 UTC
Labels: bug, in progress
