### ISSUE TITLE
MSFT_SPSearchTopology: Cannot bind argument to parameter 'SearchServiceInstance' because it is null. (FQDN Server Name)

### ISSUE THREAD

**Issue by ChristophHannappel** [dsccommunity/SharePointDsc#1031] opened 2019-02-26 09:32 UTC
#### Details of the scenario you tried and the problem that is occurring
I'm trying to set the search topology with FQDN Servernames, so i can use my AllNode Data to configure the topology without having a different Configuration for Stage and Produktion.
While troubleshooting I decleared the servernames directly in the configuration.
As a sanity check i ran with hostnames and the ressource creates a Topology as expected.
Every test started with a new SearchService Application without an topology.

#### Verbose logs showing the problem
VERBOSE: [ServerHostName]: LCM:  [ End    Set      ]  [[SPSearchTopology]SP-SearchTopology]  in 0.3930 seconds.
PowerShell DSC resource MSFT_SPSearchTopology  failed to execute Set-TargetResource functionality with error message: Cannot bind argument to parameter 'SearchServiceInstance' because it is null. 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : ServerHostName.Domain.tld

#### Suggested solution to the issue
I did some digging into the ressource code. The handling of FQDN Servername works. The `$AllSearchServiceInstances` Variable gets filled properly, but i suspect the issue happens on Line 363 inside the MSFT_SPSearchTopology.psm1. In the previous code the FQDN gets converted to a hostname, but not in this part. Unfortunatly my PowerShell is not good enougth for the `Build up the topology changes for each object type` part and there is a high chance I'm wrong with that. 

```powershell
 # Build up the topology changes for each object type
        @("Admin",
          "Crawler",
          "ContentProcessing",
          "AnalyticsProcessing",
          "QueryProcessing",
"IndexPartition") | ForEach-Object -Process {
....
```
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
SPSearchTopology SP-SearchTopology
            {
                DependsOn = '[SPSearchServiceApp]SP-SearchService'
                PsDscRunAsCredential    = $DSCAccount
                ServiceAppName          = "SearchService_Default"
                Admin                   = @('FQDN#1','FQDN#2')
                Crawler                 = @('FQDN#1','FQDN#2')
                ContentProcessing       = @('FQDN#1','FQDN#2')
                AnalyticsProcessing     = @('FQDN#1','FQDN#2')
                QueryProcessing         = @('FQDN#1','FQDN#2')
                FirstPartitionDirectory = ($ConfigurationData.NonNodeData.SPSearchTopologyIndexPath + '\SearchService_Default\Partition0')
                IndexPartition          = @('FQDN#1','FQDN#2')
```

#### The operating system the target node is running
```PowerShell
OsName               : Microsoft Windows Server 2016 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 14393.2724.amd64fre.rs1_release.181231-1751
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
```

#### Version of SharePoint that is used (e.g. SharePoint 2016)
SharePoint 2016
#### Version and build of PowerShell the target node is running
PSVersion 5.1.14393.2636 
PSEdition Desktop
PSCompatibleVersions {1.0, 2.0, 3.0, 4.0...}
BuildVersion 10.0.14393.2636
CLRVersion 4.0.30319.42000
WSManStackVersion 3.0
PSRemotingProtocolVersion 2.3
SerializationVersion 1.1.0.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
3.1.0.0

**Comment by MikeLacher448** [comment] 2019-03-08 15:26
We are seeing this as well, (using version 2.5 of the resource) we need to use FQDN in our environment configs because the user accounts we use to compile the config are on a different domain than the servers.

**Comment by wfeaser** [comment] 2019-03-12 11:16
In version 2.5 of the resource, the issue is caused by the presence of the FQDN in the $ComponentsToAdd and the $ComponentsToRemove arrays.  These arrays are populated directly from the function input parameter.  The issue can be resolved by adding the following to the Set-TargetResource method.

1. Create the $domain variable somewhere around line 229 (inside the Invoke-SPDSCCommand script block).  Variable should be populated using the exact code that is used to populate it in the Get method.
2. Immediately prior to the foreach loop based on $ComponentsToAdd (~line 377), add the following line:  $ComponentsToAdd = $ComponentsToAdd -Replace ".$domain"
3. Immediately prior to the foreach loop based on $ComponentsToRemove (~line 418), add the following line:  $ComponentsToRemove = $ComponentsToRemove -Replace ".$domain"

**Comment by wfeaser** [comment] 2019-03-13 11:57
The code in my previous comment will fix the issue with the Set method, but the next issue that occurs when using FQDN is with the Test method.  In the resource's current implementation, the Test method will always fail when using the FQDN because the Get method returns the NetBIOS name.  For my current customer, I went back to the original version of this resource and addressed the FQDN vs NetBIOS name issue in the configuration script (ie - the node data file uses FQDN everywhere except in the Search Topology section and the configuration script has logic to handle translations in instances where nodename needs to be compared to topology elements, such as for identifying the first index server).

**Comment by ruandersMSFT** [comment] 2020-03-31 19:58
First identified bug on line 401 contains two $ signs and does not map to the correct value.

![image](https://user-images.githubusercontent.com/16927960/78069526-7e81b480-7357-11ea-8e29-6860b44f250c.png)

**Comment by ruandersMSFT** [comment] 2020-04-01 16:20
With the code change in place for fixing SearchServiceInstance, the null reference exception was fixed and a new error is presented:

![image](https://user-images.githubusercontent.com/16927960/78161234-6155f000-7402-11ea-8a1d-9c96627ee443.png)

**Comment by ykuijs** [comment] 2021-06-23 12:17
Finally got around to investigate this issue. The issue is located on multiple places:
- The Get method always returns NetBIOS names, but the Test methods compares the desired and current state 1-on-1, which will always result in false being returned from the Test method when using FQDNs in the desired config.
- As specified by @wfeaser: During population of the ComponentsToAdd and ComponentsToRemove variables, domains are not taken into account. When the desired state uses FQDN, the config will try to add the FQDN to the topology and will try to remove the NetBIOS name from the topology, which is not present in the topology.

I am implementing fixes to both issues, but currently I do not have an environment which is using FQDNs which I can test this on. Does anyone have an environment available that is using FQDNs which can test the solution for me?

**Closed** 2021-07-08 20:15 UTC
Labels: bug, in progress
