### ISSUE TITLE
Not recognizing admin and SPOsite:

### ISSUE THREAD

**Issue by soundd2** [dsccommunity/SharePointDsc#1387] opened 2022-02-21 05:54 UTC
Not recognizing admin and SPOsite:

I used below code:
![image](https://user-images.githubusercontent.com/94822959/154897231-bcd5f544-3967-48dd-80af-dff5ffbf21a5.png)
Please help

**Comment by ykuijs** [comment] 2022-02-21 11:58
Hi @soundd2,

You are using Microsoft365DSC, this repository is for SharePointDsc which is a different module.

Please create issues for Microsoft365DSC at: https://github.com/microsoft/Microsoft365DSC

But I do know the cause of this issue: You are using the GlobalAdminAccount parameter. This parameter was recently renamed to Credential. You can find the documentation for this resource here: https://microsoft365dsc.com/resources/sharepoint/SPOSite/

**Comment by soundd2** [comment] 2022-02-21 13:08
Hi Yorick Kujjis,

I am glad that you responded, thank you. But after changing to credentials
also it is not recognizing. Please help
[image: image.png]

Regards
Shyam

**Comment by ykuijs** [comment] 2022-02-21 20:50
The screenshot is not showing.

SharePointDsc (this repository) is targeting on-premise SharePoint: 2013, 2016, 2019 or Subscription Edition.

However you are trying to configure SharePoint Online, which is part of Microsoft 365 and which can be configured using Microsoft365DSC. This is also mentioned in your configuration:
> Import-DscResource -ModuleName **_Microsoft365DSC_**

**Comment by soundd2** [comment] 2022-02-25 05:35
Hi Yorick Kuijs,

I have tried to add a SharePointDSC module, but it is not recognizing it
seems. Please help. PFA
[image: image.png]


Regards
Shyam

**Comment by ykuijs** [comment] 2022-02-25 07:54
Hi @soundd2,

The screenshot is missing in your message. When you add a screenshot via mail, it is not added to the message in GitHub. Could you please add it directly in GitHub, not via mail?

Also, can you please explain what you are trying to accomplish? And the steps you are taking to do that? Share your configs, etc?

**Comment by andikrueger** [comment] 2022-02-25 07:59
@ykuijs this issue is related to SharePoint Online and Microsoft 365 DSC - or at least I think so. 

@soundd2 could you share your use case, so that we can elaborate the right topic. Thanks

**Comment by soundd2** [comment] 2022-02-25 08:06
HI Andi,

here is the screenshot, How to get rid of below error.
![image](https://user-images.githubusercontent.com/94822959/155678148-d411e120-4364-4e98-bd47-2eebd2d233a3.png)

Use case , I want to use Microsoft DSC and perform a testing on SharePoint Online site collection and SP Online admin centre 
and eventually  I want to perform CI/CD 
I have been struggling but failing to get rid of the below error and other error for other ticket:
![image](https://user-images.githubusercontent.com/94822959/155678051-9e284827-c353-4bde-a421-c9a41c346641.png)

If u could help me with steps to be performed to get rid of these errors and also  I have gone through DSC tutorials and MS links to understand and implementing but in process getting these errors.

**Comment by andikrueger** [comment] 2022-02-25 08:09
SharePointDSC is for SharePoint Server (On-Premises). We should proceed with the issue in Microsoft365DSC repository as this is related to cloud services.

**Comment by soundd2** [comment] 2022-02-25 08:10
Can u please transfer to Microsoft 365 dSC thank you

**Comment by ykuijs** [comment] 2022-02-25 08:19
Hi @soundd2,

Unfortunately GitHub does not allow to transfer issues between repositories. Could you please recreate the issue in Microsoft365DSC.

Looking at the above screenshots, a comment: You can't run the Import-DscResource outside a DSC configuration.

PowerShell Desired State Configuration is a framework which you can use to implement Infrastructure as Code / Configuration as Code practices. Out of the box it is only able to configure a few basic components like registry, Windows Features, etc. To extend this functionality, you can install modules. Each module targets a specific technology.
- SharePointDsc: SharePoint on-premise environments, like SharePoint 2019 or Subscription Edition. The name of these resources all start with SP*
- Microsoft365DSC: Microsoft 365 workloads, like SharePoint Online. The name of SharePoint Online resources all start with SPO*

I recommend viewing this very good training series by Jason Helmick and Jeffrey Snover to get started with DSC: https://docs.microsoft.com/en-us/shows/getting-started-with-powershell-dsc/

Or these:
- https://docs.microsoft.com/en-us/shows/sharepoint-automation-with-dsc/video-introduction-to-powershell-dsc
- https://docs.microsoft.com/en-us/shows/sharepoint-automation-with-dsc/demo-creating-sample-files
- https://docs.microsoft.com/en-us/shows/sharepoint-automation-with-dsc/demo-securing-a-.mof-file

**Comment by ykuijs** [comment] 2022-04-08 21:23
Closing since this is for Microsoft365DSC, which is a different module.

**Closed by ykuijs** 2022-04-08 21:23 UTC
