### ISSUE TITLE
Unable to edit SPSite Description

### ISSUE THREAD

**Issue by EtsHere** [dsccommunity/SharePointDsc#1171] opened 2020-02-18 08:06 UTC
After creating SPSite with or without Description. Works and Description is set.
Edit description. Rerun script.
Description remains the same.

**Comment by ykuijs** [comment] 2020-02-18 19:10
This is by design. The Description is the description of the root web, which is a property that is editable by site collection owners. This means that if a SC owner changes the description, the SPSite resource becomes in-compliant.

When the LCM has been configured as "ApplyAndAutocorrect", this can result in a battle between the SC owner and DSC, changing the description back and forth.

That is why we specified that SharePointDsc should not update any data inside of a site collection, see bullet 4 in the [Design Guidelines](https://github.com/dsccommunity/SharePointDsc/wiki/Contributing%20to%20SharePointDsc#design-guidelines).

Closing this issue, because the behavior is by design. Let us know if you have any additional comments by adding to this issue.

**Closed by ykuijs** 2020-02-18 19:10 UTC
Labels: by design
