### ISSUE TITLE
SPVisioServiceApp errors with ''New-SPVisioServiceApplication' is not recognized as the name of a cmdlet'

### ISSUE THREAD

**Issue by matthorgan** [dsccommunity/SharePointDsc#790] opened 2018-03-27 13:11 UTC
**Details of the scenario you try and problem that is occurring:**

Using the SPVisioServiceApp resource, the DSC configuration errors during Set-TargetResource with the following 'The term 'New-SPVisioServiceApplication' is not recognized as the name of a cmdlet'. This is also happening with the SPExcelServiceApp resource. I believe this is the same as #372

The error only occurs initially - in subsequent ConfigurationStatus logs, both Visio and Excel complete successfully with no errors.  

**The DSC configuration that is using the resource:**
                SPVisioServiceApp 'VisioServiceApplication' {
                    Ensure               = 'Present'
                    Name                 = 'Visio_Services'
                    ProxyName            = 'Connection to Visio_Services'
                    ApplicationPool      = 'SPS_App_Pool'
                }

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows 2012 R2, PS version 5.1.14409
**Version of SharePoint that is used (e.g. SharePoint 2016):**
SharePoint 2013

**Version of the DSC module you're using:**
2.2.0.0 (Also tested with 2.1.0.0)

**Comment by matthorgan** [comment] 2018-03-28 13:29
On further testing, I have noticed the following:

## Test 1 - This produces a successful build with no errors:
1. Comment out the Visio/Excel resources from the script and run the SharePoint configuration. 
1. Uncomment the Visio/Excel resources and run the configuration again

## Test 2 - This errors but only the first time the resources are executed:
1. Leave the Visio/Excel resources uncommented as part of the main SharePoint configuration script and run the SharePoint Configuration. 

Could this be some sort of timing issue? Both the Excel and Visio resources depend on the SPFarm to be available before running.

**Comment by ykuijs** [comment] 2018-03-29 07:22
Hi @matthorgan This might be a timing issue indeed. Does your config implement dependencies, so having the provisioning of SharePoint components (service apps, web apps, etc) depend on the creation of the farm?

If not, can you test if this issue also occurs when you implement that?

At the same time:
The resource currently does not contain a check to see if the farm exists. It would be good to add this check.

**Comment by matthorgan** [comment] 2018-03-29 14:07
Hi @ykuijs, unfortunately, the config already has dependencies set. Here is an extract from the configuration showing the 'DependsOn' chain for the resource : 

```
# Set Farm variable for 'DependsOn' parameter
if ($Node.Roles -contains 'Application') {
    $farmReadyResourceName = '[SPFarm]SharePointFarm'
} 
else {
    $farmReadyResourceName = '[SPFarm]JoinSPFarm'
}

# Start the Visio Graphics Service
SPServiceInstance 'StartVisioGraphicsServiceInstance' {
    Ensure               = 'Present'
    Name                 = 'Visio Graphics Service'
    PsDscRunAsCredential = $Node.PSDscRunAsCredential
    DependsOn            = $farmReadyResourceName
}
# Create VisioService Application
SPVisioServiceApp 'VisioServiceApplication' {
    Ensure               = 'Present'
    Name                 = 'Visio_Services'
    ProxyName            = 'Connection to Visio_Services'
    ApplicationPool      = 'SPS_App_Pool'
    PsDscRunAsCredential = $Node.PSDscRunAsCredential
    DependsOn            = '[SPServiceInstance]StartVisioGraphicsServiceInstance'
}
```

**Comment by andikrueger** [comment] 2018-03-29 16:36
Could you try to add an additional dependency for the application pool 'SPS_App_Pool' resource? Maybe the pool is not available.

**Comment by matthorgan** [comment] 2018-03-30 15:56
That's a fair point @andikrueger. I added the resource pool dependcy to the SPVisioServiceApp but ran into the same issue with the error message `The term 'New-SPVisioServiceApplication' is not recognized as the name of a cmdlet`.

**Comment by andikrueger** [comment] 2018-03-30 17:04
Thank you for your feedback @matthorgan. 

Your error suggest, that there could be something wrong with `Invoke-SPDSCCommand`. This function is used load the SharePoint Snap-in and to execute the command as the PsDscRunAsCredential Account. But, an error with this function seems to be very unlikely.

Currently I can think of the following options to get more details on this error:

1. Could you check the credential reference in your mof-file. Is the account used to run this resource an farm/install account?
2. Is there any chance you could share the verbose log of these resources? `Start-DscConfiguration -Verbose -Wait ...`
3. Are there any custom resources in your configuration, that do load the `Microsoft.SharePoint.PowerShell.dll`?

**Comment by matthorgan** [comment] 2018-03-31 15:06
Hi @andikrueger,

Here are the responses to your questions:

1. The credential reference in the MOF file is the same account that installs the farm - I've just used one domain admin account for everything in my lab.
2. Please see attached for the before and after DSC JSON files.
3. No custom resources in the configuration - everything is from the SharePointDSC module.

In the meantime, I am going to spin up a different Vagrant box to rule out any funky stuff at the VM template level.

[DSCLogs.zip](https://github.com/PowerShell/SharePointDsc/files/1865593/DSCLogs.zip)

**Comment by andikrueger** [comment] 2018-03-31 16:20
Thank you for the logs. The logs seem to be okay and I can't see, why the cmdlets are not available... 

But, one other thing did strike my eye: Your logs of the second configuration run do show something interesting. All your managed accounts are not in their desired state. The Set-Methood of the SPManagedAccount resource is not skipped - all other resources (excluding excel-services and visio-services) do skip the set-method. Maybe this is related to the errors you are seeing.

**Comment by matthorgan** [comment] 2018-04-02 15:48
Hi @andikrueger. I span up a new lab using my updated Vagrant boxes in the long-shot hope that I saw some improvement but it's failing at the same place and with the same error.

That's interesting re the logs - it looks like on the second configuration run, the DSC is updating the settings for the managed accounts which is strange seeing as it is using the same MOF file as the first run. 

What's the best way to debug the configuration? I looked at using Enable-DscDebug but as SPFarm reboots the box, I'm not sure on how to isolate the Excel/Visio resources.

**Comment by andikrueger** [comment] 2018-04-02 20:31
`Enable-DscDebug` is necessary, so that you can debug the resources used to apply your configuration. you could set your LCM to not continue the configuration after a reboot and start the configuration by hand. 
SharePointDsc makes use of `Invoke-Command`. This function weill be called by the `Invoke-SPDSCCommand` and adds the PS SanpIn for SharePoint to the script block and will also switch the identity, when the `InstallAccount` is set. This setting is challenging when debugging the SharePointDsc Resources.

I would start with isolating the Excel and Visio resources in the following way:
1. Create a configuration, that installs SharePoint and creates the Farm with all other settings
2. Create a configuration for Excel, that includes all Accounts, Prereqs (App Pool, Managed Account) and the settings for Excel Services. (same applies for Visio)
3. Apply the configurations in order

If the error persists: Try to reapply the failing configuration:
1. If error: Step through the resource and check if the SharePoint SnapIn is available.
2. If no error: Remove (Ensure=Absent) the latest configuration and apply (Ensure=Present) the configuration again in debug mode.

**Comment by matthorgan** [comment] 2018-04-03 18:16
Hi @andikrueger, thanks for the info - very useful. I realised that the media I was given for our SP install is actually extremely old (SharePoint 2013 SP1 15.0.4569.1000). I added an SPProductUpdate and SPConfigWizard resource to install the latest update (​March 2018 CU 15.0.5015.1000) and now I'm getting consistent builds with no errors from Visio or Excel. 

As I was using such an old version of SP, I'm not exactly sure where the fix was introduced or what fixed it but I can confirm that on 15.0.5015.1000, everything is building as expected.

**Comment by ronx** [comment] 2018-04-09 18:48
Ran into this same issue on a SP2016 build with WS2016 servers. I was running the config explicitly only for the CA server (first app server) after the first couple phases of the config (farm provisioning/joining, web apps/pools created) went through successfully and the config had completed on all other (non-CA) servers. So, I don't think it's a timing issue since there wasn't really anything else going on and it depends on the main service app pool resource.

```
VERBOSE: [plaSP1]: LCM:  [ Start  Resource ]  [[SPVisioServiceApp]VisioServiceApp]
VERBOSE: [plaSP1]: LCM:  [ Start  Test     ]  [[SPVisioServiceApp]VisioServiceApp]
VERBOSE: [plaSP1]:                            [[SPVisioServiceApp]VisioServiceApp] Testing Visio Graphics service app 'Visio Service Application'
VERBOSE: [plaSP1]:                            [[SPVisioServiceApp]VisioServiceApp] Getting Visio Graphics service app 'Visio Service Application'
VERBOSE: [plaSP1]:                            [[SPVisioServiceApp]VisioServiceApp] Executing as the local run as user CONTOSO\spsetup
VERBOSE: [plaSP1]:                            [[SPVisioServiceApp]VisioServiceApp] Leaving BeginProcessing Method of Get-SPServiceApplication.
VERBOSE: [plaSP1]:                            [[SPVisioServiceApp]VisioServiceApp] Leaving ProcessRecord Method of Get-SPServiceApplication.
VERBOSE: [plaSP1]:                            [[SPVisioServiceApp]VisioServiceApp] Leaving EndProcessing Method of Get-SPServiceApplication.
VERBOSE: [plaSP1]: LCM:  [ End    Test     ]  [[SPVisioServiceApp]VisioServiceApp]  in 0.1410 seconds.
VERBOSE: [plaSP1]: LCM:  [ Start  Set      ]  [[SPVisioServiceApp]VisioServiceApp]
VERBOSE: [plaSP1]:                            [[SPVisioServiceApp]VisioServiceApp] Setting Visio Graphics service app 'Visio Service Application'
VERBOSE: [plaSP1]:                            [[SPVisioServiceApp]VisioServiceApp] Getting Visio Graphics service app 'Visio Service Application'
VERBOSE: [plaSP1]:                            [[SPVisioServiceApp]VisioServiceApp] Executing as the local run as user CONTOSO\spsetup
VERBOSE: [plaSP1]:                            [[SPVisioServiceApp]VisioServiceApp] Leaving BeginProcessing Method of Get-SPServiceApplication.
VERBOSE: [plaSP1]:                            [[SPVisioServiceApp]VisioServiceApp] Leaving ProcessRecord Method of Get-SPServiceApplication.
VERBOSE: [plaSP1]:                            [[SPVisioServiceApp]VisioServiceApp] Leaving EndProcessing Method of Get-SPServiceApplication.
VERBOSE: [plaSP1]:                            [[SPVisioServiceApp]VisioServiceApp] Creating Visio Graphics Service Application Visio Service Application
VERBOSE: [plaSP1]:                            [[SPVisioServiceApp]VisioServiceApp] Executing as the local run as user CONTOSO\spsetup
VERBOSE: [plaSP1]: LCM:  [ End    Set      ]  [[SPVisioServiceApp]VisioServiceApp]  in 0.5780 seconds.
PowerShell DSC resource MSFT_SPVisioServiceApp  failed to execute Set-TargetResource functionality with error message: The term 'New-SPVisioServiceApplication' is not recognized as the name of a cmdlet, function, script file, or 
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : plasp1
```

I remoted into this box and ran Start-DscConfiguration -Wait -UseExisting -Verbose and it finished with no errors and provisioned the Visio service app. Maybe something is getting unloaded during the Set-TargetResource of an earlier resource and that's why it works the 2nd time through since the Set's are skipped? It doesn't seem likely since there are other services that are created in the first run AFTER the Visio service fails, like SPUserProfileServiceApp. Just grasping at straws. I can send you guys the complete logs for 1st and 2nd runs if you're interested.

**Comment by andikrueger** [comment] 2018-04-10 04:59
Puh. I really hoped it was something caused by old versions or timeing. 

Could you do a few checks of your windows event logs?
1. There should be an entry for the error message above under the powershell dsc Node. Can you get the timestamp of the message
2. Is there any other message related to the SharePoint PowerShell Add-In Associated with the timestamp from 1?
3. Are there any other errors, warnings, information associated with 1.?

Please correct me if I'm wrong: the error says: DSC can not find the cmdlet, that is part of SharePoint. This means the SharePoint add-In was not loaded (correctly).

**Comment by ronx** [comment] 2018-04-13 20:02
There are 3 error entries in the DSC event log with that timestamp:

```
Job {DD64D794-3C0B-11E8-A948-000D3A179035} : 
Message The term 'New-SPVisioServiceApplication' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. 
HResult -2146233087 
StackTrack    at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
   at System.Management.Automation.PowerShell.CoreInvokeRemoteHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.ResourceProviderAdapter.ExecuteCommand(PowerShell powerShell, ResourceModuleInfo resInfo, String operationCmd, List`1 acceptedProperties, CimInstance nonResourcePropeties, CimInstance resourceConfiguration, LCMDebugMode debugMode, PSInvocationSettings pSInvocationSettings, UInt32& resultStatusHandle, Collection`1& result, ErrorRecord& errorRecord, PSModuleInfo localRunSpaceModuleInfo)

Job {DD64D794-3C0B-11E8-A948-000D3A179035} : 
This event indicates that failure happens when LCM is processing the configuration. Error Id is 0x1. Error Detail is The SendConfigurationApply function did not succeed.. Resource Id is [SPVisioServiceApp]VisioServiceApp and Source Info is C:\temp\SPPLA_DSCConfig.ps1::962::21::SPVisioServiceApp. Error Message is PowerShell DSC resource MSFT_SPVisioServiceApp  failed to execute Set-TargetResource functionality with error message: The term 'New-SPVisioServiceApplication' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. .

Job {DD64D794-3C0B-11E8-A948-000D3A179035} : 
MIResult: 1
Error Message: PowerShell DSC resource MSFT_SPVisioServiceApp  failed to execute Set-TargetResource functionality with error message: The term 'New-SPVisioServiceApplication' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. 
Message ID: ProviderOperationExecutionFailure
Error Category: 7
Error Code: 1
Error Type: MI
```

Let me know if you'd like for me to email you the verbose logs from the first run (when it failed) and the follow-up run when it succeeded.

**Comment by andikrueger** [comment] 2018-04-14 07:35
Thank you for the log entries. I was hoping to get more information out of the log messages, but I couldn't find anything significant.

Let's focus on what could possibly go wrong:
The `Set-TargetResource` function calls the `Get-TargetResource` function successfully - this includes loading the SharePoint Add-In.
After the `Get-TargetResource` function call another `Invoke-SPDSCCommand` is triggered.
I see the following failure possibilities:
1. Probably the old Add-In is still loaded and the new `Invoke-SPDSCCOmmand` does not add the Add-In. The old Add-In gets removed before the function call.
2. The `Invoke-SPDSCCommand` does not load the Add-In correctly.
3. An error occurs loading the Add-In (This should be logged in windows event log or maybe the ULS log)

Could you please test the following:
Could you remove the SPVisioServiceApp and reapply the configuration? Is there still the error on the first run and does the second run succeed?

**Comment by ykuijs** [comment] 2018-04-26 08:37
The SPDsc code is adding the following code to each command it is running:
```
if ($null -eq (Get-PSSnapin -Name Microsoft.SharePoint.PowerShell -ErrorAction SilentlyContinue))
{
    Add-PSSnapin Microsoft.SharePoint.PowerShell
}
```

This implies that the snapin should always be loaded, however I have seen instances in the past (non SPDsc related) where Get-PSSnapin returned the snapin as loaded, but you were still unable to use any cmdlets. Have to find our what the cause of this issue was, so we can check if this has the same cause.

**Comment by ykuijs** [comment] 2020-10-27 16:17
Since this issue was last updated 2.5 years ago, I am going to close this issue. If the issue still occurs, please add a comment to this issue and include as much details as possible, so we can continue troubleshooting.

**Closed by ykuijs** 2020-10-27 16:17 UTC
Labels: enhancement, needs investigation
