### ISSUE TITLE
SPFarmAdministrators: SPFarmAdministrators fails with "An item with the same key has already been added"

### ISSUE THREAD

**Issue by IlleNilsson** [dsccommunity/SharePointDsc#1217] opened 2020-06-26 13:04 UTC
Error Message: PowerShell DSC resource MSFT_SPFarmAdministrators  failed to execute Set-TargetResource
                  functionality with error message: An item with the same key has already been added

#### Details of the scenario you tried and the problem that is occurring
Just added one AD-group to Members in resource SPFarmAdministrators

#### Suggested solution to the issue
Case insensitive search of groups and accounts before adding them to Lists and Dictionaries

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

PowerShell DSC:
            SPFarmAdministrators 'FarmAdministrators' {
                PsDscRunAsCredential = $SetupCredential
                IsSingleInstance = 'Yes'
                Members = @($ConfigurationData.NonNodeData.SharePoint.AdministratorsGroup) +
                    @($ConfigurationData.NonNodeData.SharePoint.MonitorsGroup) | ? { $_ }
                DependsOn = @('[SPFarm]Farm')
            }

MOF:
instance of MSFT_SPFarmAdministrators as $MSFT_SPFarmAdministrators1ref
{
ResourceID = "[SPFarmAdministrators]FarmAdministrators";
 PsDscRunAsCredential = $MSFT_Credential29ref;
 Members = {
    "<DOMAIN>\\SpIntAdmins"
};
 SourceInfo = "C:\\Users\\JhonDoe\\repos\\Source\\DSC\\~Config\\SPFarmDSC.ps1::785::13::SPFarmAdministrators";
 IsSingleInstance = "Yes";
 ModuleName = "SharePointDsc";
 ModuleVersion = "4.2.0";

DependsOn = {

    "[SPFarm]Farm"};

 ConfigurationName = "SPFarmDSC";

};

#### The operating system the target node is running
OsName               : Microsoft Windows Server 2016 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 14393.3750.amd64fre.rs1_release.200601-1853
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of SharePoint that is used (e.g. SharePoint 2016)
SharePoint 2016

#### Version and build of PowerShell the target node is running
Name                           Value
----                           -----
PSVersion                      5.1.14393.3471
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.3471
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
#### Version of the DSC module that was used
ModuleVersion = "4.2.0";

**Comment by IlleNilsson** [comment] 2020-07-10 07:47
Found an entry in the new Event Log SPDsc. Farm Administrators group does not match the specified MembersActual: BUILTIN\administrators, <DOMAIN>\dscsetup, <DOMAIN>\spintfarm. Desired: <DOMAIN>\SpIntAdmins

**Comment by IlleNilsson** [comment] 2020-07-10 08:58
Added all these accounts to SPFarmAdministrators.Members and get a failure that BUILTIN\Administrators can't be resolved, of course.

**Comment by IlleNilsson** [comment] 2020-07-10 09:02
Changed from Members property to MembersToInclude and get this: <DOMAIN>\SpIntAdmins is not a Farm Administrator, but is included in MembersToInclude: <DOMAIN>\DscSetup, <DOMAIN>\SpIntFarm, <DOMAIN>\SpIntAdmins. Well yes, but isn't SPFarmAdministrators suposed to add the <DOMAIN>\SpIntAdmins group as SharePoint Administrators? It did in version 3.8.0 and earlier.

**Comment by ykuijs** [comment] 2020-07-10 12:26
You are absolutely right that using the Members parameter should configure just the accounts specified in there. Will have to do some investigation into what is going on here.

**Comment by IlleNilsson** [comment] 2020-07-10 12:35
Thanks, I’ve tried for a PR but I’m not too good at debugging DSC.

If you have any good resources of how to debug DSC, please send them to me and I’ll work on my DSC debugging skils.

BR // Ilian

**Comment by ykuijs** [comment] 2020-07-10 12:38
The easiest is to enable debugging and use the ISE to step through the code:
https://docs.microsoft.com/en-us/powershell/scripting/dsc/troubleshooting/debugresource

Just create a config with just this resource and push that to the server. As soon as the deployment is started it will wait for a breakpoint and display the information you can use in another ISE instance to connect to the process. After that you can step through the code.

**Comment by ykuijs** [comment] 2020-07-10 12:43
@IlleNilsson Can you share the DSC verbose logging of the SPFarmAdministrators resource for this issue and the issue when adding BUILTIN\Administrators?

**Comment by ykuijs** [comment] 2020-07-10 12:44
FYI: You can use the script you find [here](https://raw.githubusercontent.com/ykuijs/Powershell/master/Dsc/DSCLogParser.ps1) to check find the logs of all previous DSC runs.

**Comment by IlleNilsson** [comment] 2020-07-10 12:51
Thanks

**Comment by IlleNilsson** [comment] 2020-07-10 12:51
Thanks

**Comment by IlleNilsson** [comment] 2020-07-10 12:55
I only added BUILTIN\Adminstrators since it was in the original error log entry as to what should be there as SP Farm Administrators.

I’ve never wanted BUILTIN\Adminstrators to be an SP Farm Administrator.

I’ll try to get the logs out for you. I’m going on holiday for three week, sailing, so I’ll try on a rainy day in a port.

Thanks a bunch for all the work you and others do for the OS community.

BR // Ilian

**Comment by ykuijs** [comment] 2020-07-10 12:59
I agree with that, usually the Domain Admins are also part of the BUILTIN\Administrators and you don't want them to also be SharePoint Admin. But since you said that you got an error when adding that group, I was wondering what that could have been. 

Since the group was already in there, it doesn't make sense it reported that it could not be resolved. I also just tried to add the group on my test environment and there it worked just fine.

Have a great vacation!

**Comment by ykuijs** [comment] 2020-07-30 20:13
Just tried to reproduce. It works on SP2019, but on SP2016 I am getting the same error! Now working on finding the root cause!

**Comment by ykuijs** [comment] 2020-07-30 20:48
Found the root cause. Now figuring out how to solve it :-)

**Comment by ykuijs** [comment] 2020-07-30 21:14
Issue resolved, will be included in my next bugfix PR

**Comment by IlleNilsson** [comment] 2020-07-31 02:44
Thanks a lot, you Rock!

________________________________

**Closed** 2020-09-15 07:33 UTC
Labels: bug, in progress
